### ISSUE TITLE
Error while running the Karma task through frontend-maven-plugin

### ISSUE THREAD

**Issue by keerthana-raman** [eirslett/frontend-maven-plugin#127]
I get an error while trying to use the frontend-maven-plugin to run Jasmine Karma tests

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.19:karma (javascript tests) on project karmaTest: Failed to run task: 'karma start src/test/javascript/karma.conf.ci.js --no-colors' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.19:karma (javascript tests) on project karmaTest: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.KarmaRunMojo.execute(KarmaRunMojo.java:57)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'karma start src/test/javascript/karma.conf.ci.js --no-colors' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:38)
	at com.github.eirslett.maven.plugins.frontend.mojo.KarmaRunMojo.execute(KarmaRunMojo.java:51)

**Comment by pax2k** [comment]
I had a similar problem on my Mac. 

My project and “eirslett/frontend-maven-plugin” failed with:


“[INFO] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.21-SNAPSHOT:karma (javascript tests) on project example: Failed to run task: 'karma start src/test/javascript/karma.conf.ci.js --no-colors' failed. (error code 1) -> [Help 1]“

Searched the Internet and found this post:
http://www.sencha.com/forum/showthread.php?231282-dyld-lazy-symbol-binding-failed-Symbol-not-found-on-OS-X

Followed the steps:
cd /usr/local/lib
sudo rm libssl*
sudo ln -s /usr/lib/libssl.dylib libssl.dylib
sudo ln -s /usr/lib/libssl.0.9.8.dylib libssl.0.9.8.dylib

And now it is working:
[INFO] Reactor Summary:
[INFO] 
[INFO] Frontend Plugins .................................. SUCCESS [1.089s]
[INFO] frontend-plugin-core .............................. SUCCESS [5.288s]
[INFO] Maven Frontend Plugin ............................. SUCCESS [1:17.528s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by eirslett** [comment]
Ok, thanks for figuring it out!
