### ISSUE TITLE
jenkins cannot run program

### ISSUE THREAD

**Issue by nateinindy** [eirslett/frontend-maven-plugin#147]
I receive the following when trying to run my build via jenkins.

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:npm (npm install) on project myapp: Failed to run task: 'npm install --color=false' failed. java.io.IOException: Cannot run program "/export/home/webadmin/.jenkins/jobs/stuff-develop-2014-Q4-apps/workspace/com.company.app/myapp/node/node" (in directory "/export/home/webadmin/.jenkins/jobs/stuff-develop-2014-Q4-apps/workspace/com.company.app/myapp"): error=22, Invalid argument -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:npm (npm install) on project myapp: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.jvnet.hudson.maven3.launcher.Maven3Launcher.main(Maven3Launcher.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:329)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:239)
	at org.jvnet.hudson.maven3.agent.Maven3Main.launch(Maven3Main.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:134)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:69)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:52)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 30 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'npm install --color=false' failed.
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:41)
	at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:50)
	... 32 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutionException: java.io.IOException: Cannot run program "/export/home/webadmin/.jenkins/jobs/stuff-develop-2014-Q4-apps/workspace/com.company.app/myapp/node/node" (in directory "/export/home/webadmin/.jenkins/jobs/stuff-develop-2014-Q4-apps/workspace/com.company.app/myapp"): error=22, Invalid argument
	at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput(ProcessExecutor.java:70)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeExecutor.executeAndRedirectOutput(NodeExecutor.java:21)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:36)
	... 33 more
Caused by: java.io.IOException: Cannot run program "/export/home/webadmin/.jenkins/jobs/stuff-develop-2014-Q4-apps/workspace/com.company.app/myapp/node/node" (in directory "/export/home/webadmin/.jenkins/jobs/stuff-develop-2014-Q4-apps/workspace/com.company.app/myapp"): error=22, Invalid argument
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput(ProcessExecutor.java:58)
	... 35 more
Caused by: java.io.IOException: error=22, Invalid argument
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:136)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 36 more

**Comment by eirslett** [comment]
Try logging into the server, go to the node/node directory, and run `./node --version`. Is it executable?

**Comment by Falci** [comment]
Same here.

The plugin are trying run node from wrong directory, from source folder, like: /workspace/project/node/node.

I had already installed node and npm. So, I removed the "install-node-and-npm" goal

**Comment by eirslett** [comment]
You'll have to use the install-node-and-npm goal; this plugin doesn't use the global version of node/npm. If you want to use the global version instead, use maven-exec-plugin.
Does it work if you add the install goal? (Don't worry, it won't overwrite your global node/npm installation, it's only scoped to the current project)

**Comment by amirjamak** [comment]
Anyone solved this problem? We are having the same situation here.

**Comment by eirslett** [comment]
Using install-node-and-npm didn't help?

**Comment by amirjamak** [comment]
Yes we execute that first, and the path is wrong. 
It is looking for ${basedir}/node/npm/bin/npm-cli.js
but it can be found in ${basedir}/node/package/bin/npm-cli.js

**Comment by amirjamak** [comment]
After removing npm install execution from the plugin, we run bower install directly, and suddenly we could execute correctly, because the npm-cli.js was found in the expected path. Weird!

**Comment by vojtechhabarta** [comment]
We have similar issue on Windows computer (node\npm\bin\npm-cli.js vs. node\package\bin\npm-cli.js), "install-node-and-npm" is successful but "npm install" fails.

```
Running 'npm install --color=false --proxy=http://<PROXY>:80' in <PATH>

module.js:340
    throw err;
          ^
Error: Cannot find module '<PATH>\node\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by eirslett** [comment]
@lfryc have you seen any similar errors?
The code is supposed to rename the "package" directory to "npm", but it looks like it fails in some cases?

**Comment by lfryc** [comment]
I guess it may fail on windows because wrong use of platform specific separator char '/'. But the original report is from unix based machine apparently.

However I have noticed a bug/deficiency in the code: if renaming of the `package` dir fails (the directory is not renamed, the `renameTo` method returns false as per spec [1] - in this case the plugin should throw exception and don't ignore the failure silently). Am I correct?

[1] http://docs.oracle.com/javase/7/docs/api/java/io/File.html#renameTo(java.io.File)

**Comment by lfryc** [comment]
We could also leverage `Files.move()` as platform-indepdent option suggested in `renameTo`'s javadoc: http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#move(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...)

**Comment by vojtechhabarta** [comment]
Yes, our bug is not probably the same problem as original report.

Another reason why `renameTo` may fail on Windows could be that some file in `packageDirectory` is locked (not yet closed, read by some antivirus, indexer or other process) in which case Windows will not allow renaming. It is strange that on my Windows machine it is working without a problem (same node and npm versions). What do you think?

**Comment by vojtechhabarta** [comment]
I am afraid that it is needed to test if `renameTo` succeeded and if not then copy files to `npmDirectory` and try delete files in `packageDirectory`.

**Comment by otonielortega** [comment]
I had the same problem with the folder 'package' not being renamed in windows.

**Comment by lfryc** [comment]
> I am afraid that it is needed to test if renameTo succeeded and if not then copy files to npmDirectory and try delete files in packageDirectory.

@vojtechhabarta :+1: would you mind to open a pull request?

**Comment by texag93** [comment]
I created a workaround for this in my pom.xml. This simply attempts to renames the /node/package directory to /node/npm. It uses the maven-antrun-plugin to run an ant task to do the rename. I used phase settings to make sure the ant task executes after install-node-and-npm, but before npm install. So far, this seems to be working.

            <plugin>
                
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>handle-frontend-maven-plugin-bug</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <move failonerror="false" verbose="true" file="${basedir}/node/package" tofile="${basedir}/node/npm"/>
                            </tasks>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <inherited>false</inherited>
                <version>0.0.23</version>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            
                            <nodeVersion>v0.12.2</nodeVersion>
                            <npmVersion>2.7.6</npmVersion>
                            <downloadRoot>http://slc05avk.us.oracle.com:8000/</downloadRoot>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by gpt559** [comment]
I'm getting the same error: 
```
[INFO] Running 'npm install --color=false' in D:\Jenkins\workspace\MyProject
[ERROR] module.js:338
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module 'D:\Jenkins\workspace\MyProject\node\npm\bin\npm-cli.js'
```
But for me it's failing because the npm install thinks* it passes, but it actually fails in the background. Then it can't find the executable. 
https://github.com/coreybutler/nvm-windows/issues/75

my "work around" is to set Jenkins to do svn "update" not a clean install. so if it passes once, it'll pass until I have to do a clean install.

**Comment by eirslett** [comment]
I think this stuff, with directory renaming, is fixed in the latest release, so it should work now. Feel free to reopen if it still doesn't work!
