### ISSUE TITLE
TeamCity Build failed

### ISSUE THREAD

**Issue by asborisov** [eirslett/frontend-maven-plugin#186]
Hey, guys!
I'm trying to build my project with TeamCity 9 and frontend-maven-plugin, but always gets exceptions and can't understand what the reason. Can somebody help me?

Stacktrace below:

[03:49:53][Step 1/1] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:bower (bower install) on project WSSED-PL: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]
[03:49:53][Step 1/1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:bower (bower install) on project WSSED-PL: Failed to run task
[03:49:53][Step 1/1] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[03:49:53][Step 1/1] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[03:49:53][Step 1/1] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[03:49:53][Step 1/1] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[03:49:53][Step 1/1] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[03:49:53][Step 1/1] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[03:49:53][Step 1/1] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[03:49:53][Step 1/1] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
[03:49:53][Step 1/1] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
[03:49:53][Step 1/1] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
[03:49:53][Step 1/1] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
[03:49:53][Step 1/1] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
[03:49:53][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:49:53][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[03:49:53][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:49:53][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:606)
[03:49:53][Step 1/1] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[03:49:53][Step 1/1] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[03:49:53][Step 1/1] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[03:49:53][Step 1/1] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[03:49:53][Step 1/1] Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
[03:49:53][Step 1/1] 	at com.github.eirslett.maven.plugins.frontend.mojo.BowerMojo.execute(BowerMojo.java:41)
[03:49:53][Step 1/1] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[03:49:53][Step 1/1] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[03:49:53][Step 1/1] 	... 19 more
[03:49:53][Step 1/1] Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'bower install' failed. (error code 1)
[03:49:53][Step 1/1] 	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:38)
[03:49:53][Step 1/1] 	at com.github.eirslett.maven.plugins.frontend.mojo.BowerMojo.execute(BowerMojo.java:39)
[03:49:53][Step 1/1] 	... 21 more
[03:49:53][Step 1/1] [ERROR] 
[03:49:53][Step 1/1] [ERROR] 
[03:49:53][Step 1/1] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[03:49:53][Step 1/1] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[03:49:53][Step 1/1] [ERROR] 
[03:49:53][Step 1/1] [ERROR] After correcting the problems, you can resume the build with the command
[03:49:53][Step 1/1] [ERROR]   mvn <goals> -rf :WSSED-PL

**Comment by jarle73** [comment]
Did you ever find out what the problem was here?

**Comment by asborisov** [comment]
Yes. There wasn't git installed on build server

**Comment by eirslett** [comment]
If you've got time, you could try sending a PR to bower, make them print a more useful error message if Git isn't found on the server ;-)

**Comment by asborisov** [comment]
That the reason why I've closed the issue. Bower printed such error, but much more higher :-)
