### ISSUE TITLE
'bower' was specified in an execution, but not found in the plugin

### ISSUE THREAD

**Issue by stevenpetryk** [eirslett/frontend-maven-plugin#188]
I'm not sure why this is happening. I'm using version 0.0.15, Node 0.10.18, and NPM 1.3.8.

Excerpt from pom.xml:

```xml
<execution>
	<id>bower install</id>
  <goals>
    <goal>bower</goal>
  </goals>

  <configuration>
    <arguments>install</arguments>
  </configuration>
</execution>
```

I also have bower listed as a devDependency in my package.json.

```js
"devDependencies": {
  "bower": "^1.4.1",
  ...
}
```

Full output of `mvn -e clean install`:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building ... Application
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] 'bower' was specified in an execution, but not found in the plugin
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: 'bower' was specified in an execution, but not found in the plugin
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindExecutionToLifecycle(DefaultLifecycleExecutor.java:1667)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindPluginToLifecycle(DefaultLifecycleExecutor.java:1525)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:1282)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:534)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Wed Apr 01 11:04:16 EDT 2015
[INFO] Final Memory: 7M/491M
[INFO] ------------------------------------------------------------------------
```

**Comment by eirslett** [comment]
The latest version is 0.0.23, I think. The bower mojo probably wasn't made yet in version 0.0.15?

**Comment by stevenpetryk** [comment]
I guess I hadn't considered that. Do you happen to know the latest version that supports Maven 2?

**Comment by eirslett** [comment]
No, unfortunately not, you'll have to try them one by one. If you look at the commit log, you can see when the bower mojo was introduced. Otherwise, I'd advise you to upgrade to Maven 3 of course - but I understand that's not always an option.

**Comment by stevenpetryk** [comment]
Ended up upgrading to Maven 3. Thanks for the help.
