### ISSUE TITLE
bower not installed properly

### ISSUE THREAD

**Issue by abrin** [eirslett/frontend-maven-plugin#194]
On initial run of the plugin, I get an error that bower cannot be found.  This can be alleviated manually by running "npm install bower" but it'd be really nice for this to be done internally.  Note, node, npm, and bower are not installed on my local machine elsewhere:

````
[INFO] --- frontend-maven-plugin:0.0.22:bower (bower install) @ browse ---
[INFO] Running 'bower install' in /Users/abrin/Documents/workspace/skope
[ERROR] 
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module '/Users/abrin/Documents/workspace/skope/node_modules/bower/bin/bower'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.Module._load (module.js:280:25)
[ERROR]     at Function.Module.runMain (module.js:497:10)
[ERROR]     at startup (node.js:119:16)
[ERROR]     at node.js:906:3
````

POM snippit:
````

			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<!-- NB! Set <version> to the latest released version of frontend-maven-plugin, 
					like in README.md -->
				<version>0.0.22</version>

				<executions>

					<execution>
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>v0.10.30</nodeVersion>
							<npmVersion>1.4.21</npmVersion>

						</configuration>
					</execution>

					<execution>
						<id>npm install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<!-- Optional configuration which provides for running any npm command -->
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>
					<!-- meed to run npm install bower; npm install grunt -->
					<execution>
						<id>bower install</id>
						<goals>
							<goal>bower</goal>
						</goals>
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>

				</executions>
			</plugin>
````

**Comment by eirslett** [comment]
Remember to add bower in the package.json, like in the example project. (It should be documented better)

**Comment by abrin** [comment]
Thanks, yes, that was the root cause.  It might be worth considering a separate "init" goal that produces a template package.json (and potentially shell scripts) for those of us starting from scratch.
