### ISSUE TITLE
NPM install on Codeship build show proxy error

### ISSUE THREAD

**Issue by deanclkclk** [eirslett/frontend-maven-plugin#198]
Hey guys:

Love the plugin and the ease of use it getting it setup. I am having an issue on my build environment, where it shows it's using a proxy that is error out. I confirm with the Codeship rep that the build doesn't need a proxy to resolve dependencies. Any way I could get this removed?

     [INFO] --- frontend-maven-plugin:0.0.20:npm (npm install) @ ccccccc-frontend ---
     [INFO] Running 'npm install --color=false --proxy=http://10.0.3.1:8123' in /home/rof/src/bitbucket.org/xxx-xxxxxx/ccccccc_web/src/main/webapp/resources/js
     [INFO] npm WARN package.json ccccc-tasks@0.1.0 No description
     [INFO] npm WARN package.json ccccccc-tasks@0.1.0 No repository field.
     [INFO] npm WARN package.json ccccccc-tasks@0.1.0 No README data
     [INFO] npm http GET https://registry.npmjs.org/grunt-istanbul-coverage
     [INFO] npm ERR! TypeError: Request path contains unescaped characters.
     [INFO] npm ERR!     at new ClientRequest (_http_client.js:73:11)
     [INFO] npm ERR!     at TunnelingAgent.exports.request (http.js:49:10)
     [INFO] npm ERR!     at TunnelingAgent.createSocket (/home/rof/src/bitbucket.org/cccc-

**Comment by eirslett** [comment]
No, the plugin picks up Maven's proxy configuration and uses it automatically/forwards it to npm. There is currently no way to turn that feature off. (You could eventually use an older version of the plugin, since before that proxy feature was introduced, but I guess that's not a good solution)
