### ISSUE TITLE
Cannot find module 'map-stream'

### ISSUE THREAD

**Issue by TheKnarf** [eirslett/frontend-maven-plugin#210]
Running the build locally on our developers macbooks and windows computers works, but trying to build it in Jenkins on Linux fails.

```
[INFO] --- frontend-maven-plugin:0.0.20:install-node-and-npm (install node and npm) @ hydra ---
[INFO] Node v0.10.31 is already installed.
[INFO] Found NPM version 1.4.27
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.20:npm (npm install) @ hydra ---
[INFO] Running 'npm install --color=false' in /var/jenkins_home/jobs/Hydra/workspace
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.20:gulp (gulp build) @ hydra ---
[INFO] Running 'gulp --no-color' in /var/jenkins_home/jobs/Hydra/workspace
[INFO] 
[INFO] Error: Cannot find module 'map-stream'
[INFO]     at Function.Module._resolveFilename (module.js:338:15)
[INFO]     at Function.Module._load (module.js:280:25)
[INFO]     at Module.require (module.js:364:17)
[INFO]     at require (module.js:380:17)
[INFO]     at Object.<anonymous> (/var/jenkins_home/jobs/Hydra/workspace/node_modules/gulp-sass/index.js:2:13)
[INFO]     at Module._compile (module.js:456:26)
[INFO]     at Object.Module._extensions..js (module.js:474:10)
[INFO]     at Module.load (module.js:356:32)
[INFO]     at Function.Module._load (module.js:312:12)
[INFO]     at Module.require (module.js:364:17)
[WARNING] Failed to getClass for org.wildfly.plugin.deployment.DeployMojo
[WARNING] Failed to getClass for org.wildfly.plugin.deployment.DeployMojo
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.956 s
[INFO] Finished at: 2015-05-06T12:28:58+00:00
[INFO] Final Memory: 13M/177M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:gulp (gulp build) on project hydra: Failed to run task: 'gulp --no-color' failed. (error code 8) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by eirslett** [comment]
Could be a network issue between Jenkins and npmjs? Can you try running the build a couple of times and see if that helps?

**Comment by TheKnarf** [comment]
If tried running 2-3 times now, but it all fails the same way.

**Comment by eirslett** [comment]
Try "npm shrinkwrap" in your project, to lock down the dependencies?

**Comment by benwestrate** [comment]
I am seeing a similar problem with a local file. It works locally but not on our ubuntu staging server.

**Comment by eirslett** [comment]
And shrinkwrap doesn't help? (Sometimes, the npm package versions are resolved differently, which leads to green builds on some machines and failures on others) Or commiting node_modules into the repository?

**Comment by benwestrate** [comment]
shrinkwrap doesn't help. The buildtemplatesObj is a js file located in a folder called gulp-utilities. It works just fine locally but throws this error on our staging server. 

```bash
Error: Cannot find module './../gulp-utilities/buildtemplatesObj'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.Module._load (module.js:280:25)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Object.<anonymous> (/development/ggp/ggp-ui-build/gulpTasks/move-to-cq.js:6:21)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Module.require (module.js:364:17)
```

**Comment by eirslett** [comment]
Hope you figured it out by now!
