### ISSUE TITLE
0.0.24 - Could not find JSPM Goal

### ISSUE THREAD

**Issue by githagman** [eirslett/frontend-maven-plugin#247]
Thanks for the plugin!

Looking at adding jspm init and then bundle-sfx to our Maven build for some build/deployment automation.

I've added this to my pom.xml.
```
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>0.0.24</version>
                <configuration>
                    <workingDirectory>src/main/resources/webroot-src</workingDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>nodeNpmInstall</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <nodeVersion>v0.12.7</nodeVersion>
                            <npmVersion>2.11.3</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npmInstallBower</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install bower</arguments>
                        </configuration>
                        <phase>generate-resources</phase>
                    </execution>
                    <execution>
                        <id>npmInstall</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>generate-resources</phase>
                    </execution>
                    <execution>
                        <id>bowerInstall</id>
                        <goals>
                            <goal>bower</goal>
                        </goals>
                        <phase>generate-resources</phase>
                    </execution>
                    <execution>
                        <id>jspmInstall</id>
                        <goals>
                            <goal>jspm</goal>
                        </goals>
                        <configuration>
                            <arguments>init</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>gulpDefault</id>
                        <goals>
                            <goal>gulp</goal>
                        </goals>
                        <phase>generate-resources</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>webroot-src/**</exclude>
                </excludes>
                <filtering>false</filtering>
            </resource>
        </resources>
```

Here's the kaboom.
```
thagman$ mvn -e install
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building DRS :: Web :: OperationalReporting 1.6.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.664s
[INFO] Finished at: Wed Jul 22 09:44:00 CDT 2015
[INFO] Final Memory: 4M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'jspm' in plugin com.github.eirslett:frontend-maven-plugin:0.0.24 among available goals grunt, install-node-and-npm, bower, karma, webpack, gulp, npm, ember -> [Help 1]
org.apache.maven.plugin.MojoNotFoundException: Could not find goal 'jspm' in plugin com.github.eirslett:frontend-maven-plugin:0.0.24 among available goals grunt, install-node-and-npm, bower, karma, webpack, gulp, npm, ember
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:267)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:185)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateLifecycleMappings(DefaultLifecycleExecutionPlanCalculator.java:280)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:193)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:112)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:129)
	at org.apache.maven.lifecycle.internal.BuilderCommon.resolveBuildPlan(BuilderCommon.java:92)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException
```

It looked like the latest release received the June 5th commit of the jspm support?  Tried to do my best to confirm it should be in the latest release, let me know if I missed something basic.

Thanks again, it's great I can automate this in Maven!

**Comment by yazybones** [comment]
You'll need to use version 0.0.25-SNAPSHOT of the plugin to get JSPM support.

**Comment by githagman** [comment]
Ah k, sorry should've looked harder.  Have .25-SNAPSHOT built!  Now I just have to bump all my dependencies to get off Java 6 so I can use Maven 3.1.1 to actually run `mvn install` using the plugin...  gotta love upgrading outdated stacks...

Thanks for getting back to me!
