### ISSUE TITLE
Node and NPM default to local version when running gulp

### ISSUE THREAD

**Issue by blackcathacker** [eirslett/frontend-maven-plugin#248]
When running gulp using the plugin, the paths for node and npm are appended onto the users default path. This causes issues when a different version is installed locally as gulp will error out instantly with the following error due to npm modules being installed with the configured version but gulp running under the locally installed one.

`[ERROR] module.js:355
[ERROR]   Module._extensions[extension](this, filename);
[ERROR]                                ^
[ERROR] Error: Module version mismatch. Expected 14, got 43.
[ERROR]     at Error (native)
[ERROR]     at Module.load (module.js:355:32)
[ERROR]     at Function.Module._load (module.js:310:12)
[ERROR]     at Module.require (module.js:365:17)
[ERROR]     at require (module.js:384:17)
[ERROR]     at Object.<anonymous> (/java/workspace/kc/coeus-webapp/src/main/jsfrontend/node_modules/aglio/node_modules/drafter/lib/drafter.js:5:15)
[ERROR]     at Module._compile (module.js:460:26)
[ERROR]     at Object.Module._extensions..js (module.js:478:10)
[ERROR]     at Module.load (module.js:355:32)
[ERROR]     at Function.Module._load (module.js:310:12)`

**Comment by KostyaSha** [comment]
In relevant PR you can add in commit message "Closes #248" and it will automatically close mentioned issue after merge.

**Comment by eirslett** [comment]
Was this fixed?
