### ISSUE TITLE
Errors on running gulp: Not Found

### ISSUE THREAD

**Issue by computerlyrik** [eirslett/frontend-maven-plugin#252]
Using the http://mean.io getting-started-app with frontend-maven-plugin, i am getting the following error

```bash
[ERROR] module.js:338
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module '${project.dir}/src/main/frontend/node_modules/gulp/bin/gulp.js'
[ERROR]     at Function.Module._resolveFilename (module.js:336:15)
[ERROR]     at Function.Module._load (module.js:278:25)
[ERROR]     at Function.Module.runMain (module.js:501:10)
[ERROR]     at startup (node.js:129:16)
[ERROR]     at node.js:814:3
```

My relevant part of pom.xml
```xml
			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>0.0.23</version>

				<configuration>
					<workingDirectory>src/main/frontend</workingDirectory>
				</configuration>


				<executions>
					<execution>
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<phase>generate-resources</phase>
						<configuration>
							<nodeVersion>v0.12.7</nodeVersion>
							<npmVersion>2.13.2</npmVersion>
						</configuration>
					</execution>
					<execution>
						<id>npm install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<phase>generate-resources</phase>
					</execution>
					<execution>
						<id>npm install deps</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install gulp</arguments>
						</configuration>
						<phase>generate-resources</phase>
					</execution>
					<execution>
						<id>gulp run</id>
						<goals>
							<goal>gulp</goal>
						</goals>
						<phase>install</phase>
					</execution>
				</executions>
			</plugin>

```

**Comment by eirslett** [comment]
You need to put gulp in your package.json file as well.
