### ISSUE TITLE
frontend-maven-plugin fails running gulp build on projects with spaces in directory path

### ISSUE THREAD

**Issue by Felteh** [eirslett/frontend-maven-plugin#289]
Plugin version 0.0.25

I am building a simple project which runs gulp build via frontend-maven-plugin. On my Jenkins servers I check out to:
/home/hostname/slave/workspace/ProjectIT/Project V2/MyProject

The space in "Project V2" seems to be throwing off the frontend-maven-plugin when it tries to run gulp build.

I get a hard to spot log message:
[Thread-4] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultGulpRunner - [11:43:38] Task never defined: V2/Build

And a stacktrace that i've limited to the important bits since I expect this is a pretty simple to re-create situation:
Waiting for Jenkins to finish collecting data
mavenExecutionResult exceptions not empty
message : Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:gulp (gulp build) on project asset-interface: Failed to run task
cause : Failed to run task
Stack trace : 
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:gulp (gulp build) on project asset-interface: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
.....

**Comment by eirslett** [comment]
Hmm... looks like it's the command logic that's acting up here. It's probably missing a quote somewhere?

**Comment by dv297** [comment]
This problem also occurs for me, a Windows example. 

[INFO] Running 'npm install --no-color' in C:\Program Files (x86)\Jenkins\jobs\Suggest UI\workspace\src
[INFO] 'C:\Program' is not recognized as an internal or external command,

**Comment by eirslett** [comment]
Which version of the plugin are you using? This problem should be fixed long ago. (The current plugin version is 1.0)

**Comment by M-Aslam** [comment]
I am receiving this error while adding these lines in my POM.xml

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			
			 <plugin>
		        <groupId>com.github.eirslett</groupId>
		        <artifactId>frontend-maven-plugin</artifactId>
		        
		        <version>1.0</version>
		        
				<executions>
		        	        
					<execution>
					    <id>install node and npm</id>
					    <goals>
					        <goal>install-node-and-npm</goal>
					    </goals>
					    <configuration>
					        <nodeVersion>v5.3.0</nodeVersion>
					        <npmVersion>3.3.12</npmVersion>
					    </configuration>
					</execution>
	                    	        	        
			        <execution>
					    <id>npm install</id>
					    <goals>
					        <goal>npm</goal>
					    </goals>
					    <configuration>
					        <arguments>install</arguments>
		
					    </configuration>
					</execution>
				
					<execution>
					    <id>gulp build</id>
					    <goals>
					        <goal>gulp</goal>
					    </goals>			
					    <configuration>
					    </configuration>
					</execution>
				</executions>
		                
	    	</plugin>
		</plugins>
	</build>

Failed to run task (com.github.eirslett:frontend-maven-plugin:1.0:gulp:gulp build:generate-resources)

org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'gulp.js ' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
	at com.github.eirslett.maven.plugins.frontend.mojo.GulpMojo.execute(GulpMojo.java:64)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
	... 32 more
