### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins

### ISSUE THREAD

**Issue by arshtepe** [eirslett/frontend-maven-plugin#293]
I have
````xml
<plugin>
       <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>0.0.23</version>
        <configuration>        
         <workingDirectory>src/main/webapp/resources</workingDirectory>
	</configuration>
			    
   	<executions>
              <execution>
	     	 <id>gulp create</id>
      	         <goals>
	              <goal>gulp</goal>
		  </goals>
	
		  <phase>generate-resources</phase>
					
		  <configuration>
	 	  <arguments>create</arguments>
		   </configuration>
	       </execution>
	</executions>
 </plugin>
````

and i have this error
````

Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on projec app: Failed to clean project: Failed to delete  .../app/target/m2e-wtp/web-resources -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project app: Failed to clean project: Failed to delete ...app/target/m2e-wtp/web-resources
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to clean project: Failed to delete ../app/target/m2e-wtp/web-resources
	at org.apache.maven.plugin.clean.CleanMojo.execute(CleanMojo.java:215)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.io.IOException: Failed to delete ../app/target/m2e-wtp/web-resources
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:249)
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:191)
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:158)
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:158)
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:117)
	at org.apache.maven.plugin.clean.CleanMojo.execute(CleanMojo.java:193)
	... 21 more
````

**Comment by eirslett** [comment]
Is it failing on your workstation or on the CI environment? You might for example have cd'ed into the directory with a terminal or something like that (opened it in a file browser?) which means it won't let you delete the file. Maybe a restart of the computer helps?

**Comment by arshtepe** [comment]
@eirslett , I updated maven to 3.3.3. But now i have error 
```
Cannot run program ".../webapp/resources/node/node"
```
Plugin need path to nodejs? 
If yes, how i can use $NODE_PATH ?

**Comment by eirslett** [comment]
You need to add the "install-node-and-npm" task first, before running gulp.

**Comment by arshtepe** [comment]
@eirslett I understand this, but how am i can use  $NODE_PATH ?
