### ISSUE TITLE
Unpacking node.tar.gz into node_tmp fails

### ISSUE THREAD

**Issue by raagu** [eirslett/frontend-maven-plugin#298]
Hello 

I have a maven based application running in ubuntu, in which I am using frontend-maven-plugin. During the build, the installation of node and npm fails with following error. 

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) on project iox-appmgr-ui: Could not extract
e: Could not extract archive: '/vagrant/ioxmgr/ioxmgr-ui/node_tmp/node.tar.gz': No such file or directory -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:install-node-and-npm (install node and n
iox-appmgr-ui: Could not extract the Node archive: Could not extract archive: '/vagrant/ioxmgr/ioxmgr-ui/node_tmp/node.tar.gz'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Could not extract the Node archive: Could not extract archive: '/vagrant/ioxmgr/ioxmgr-ui/node_tmp/node.tar.gz'
        at com.github.eirslett.maven.plugins.frontend.mojo.MojoUtils.toMojoFailureException(MojoUtils.java:13)
        at com.github.eirslett.maven.plugins.frontend.mojo.InstallNodeAndNpmMojo.execute(InstallNodeAndNpmMojo.java:83)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.InstallationException: Could not extract the Node archive
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller$NodeAndNPMInstallAction.installNodeDefault(NodeAndNPMInstaller.java:228)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller$NodeAndNPMInstallAction.install(NodeAndNPMInstaller.java:75)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller.install(NodeAndNPMInstaller.java:52)
        at com.github.eirslett.maven.plugins.frontend.mojo.InstallNodeAndNpmMojo.execute(InstallNodeAndNpmMojo.java:81)
        ... 22 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ArchiveExtractionException: Could not extract archive: '/vagrant/ioxmgr/ioxmgr-ui/node_tmp/node.tar.gz'
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtractor.extract(ArchiveExtractor.java:64)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller$NodeAndNPMInstallAction.extractFile(NodeAndNPMInstaller.java:248)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller$NodeAndNPMInstallAction.installNodeDefault(NodeAndNPMInstaller.java:199)
        ... 25 more
Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtractor.extract(ArchiveExtractor.java:43)
        ... 27 more
[ERROR]

**Comment by james-bright-helix** [comment]
@raagu did you figure this out?  I have the exact same issue.  It seems to be unable to create the destination directory.  I checked all permissions and it seems to be fine (but obviously not).

I'm wondering if it's because I'm running it in a share in vagrant with windows host/ubuntu guest.

**Comment by akoch** [comment]
You probably ran into a similar issue like https://www.virtualbox.org/ticket/11976

Unpacking the jar creates very long path names, which fails with a windows host/ubuntu guest setup.

**Comment by james-bright-helix** [comment]
Just to confirm, it was down to long path names and upgrading virtualbox and vagrant to the latest version resolved the issue.

**Comment by SkepticCoder** [comment]
Bug was reproduced. Host os: Windows 10 x86_64, client os: Cent OS 6 x86_64. Virtualbox version: 5.1.6.r110634
