### ISSUE TITLE
Failed to parse plugin descriptor for com.github.eirslett:frontend-plugin-core:0.0.26

### ISSUE THREAD

**Issue by shaiksphere** [eirslett/frontend-maven-plugin#324]
Here's the `pom.xml` snippet

```xml
<plugin>
   <groupId>com.github.eirslett</groupId>
   <artifactId>frontend-plugin-core</artifactId>
   <version>0.0.26</version>
   <executions>
      <execution>
         <id>install node and npm</id>
         <phase>initialize</phase>
         <goals>
            <goal>install-node-and-npm</goal>
         </goals>
         <configuration>
            <nodeVersion>v5.3.0</nodeVersion>
            <npmVersion>3.3.12</npmVersion>
         </configuration>
      </execution>
   </executions>
</plugin>
```

When I execute `mvn clean initialize` it fails with the following error

```
[ERROR] Failed to parse plugin descriptor for com.github.eirslett:frontend-plugin-core:0.0.26 (/home/someuser/.m2/repository/com/github/eirslett/frontend-plugin-core/0.0.26/frontend-plugin-core-0.0.26.jar): No plugin descriptor found at META-INF/maven/plugin.xml -> [Help 1]
org.apache.maven.plugin.PluginDescriptorParsingException: Failed to parse plugin descriptor for com.github.eirslett:frontend-plugin-core:0.0.26 (/home/someuser/.m2/repository/com/github/eirslett/frontend-plugin-core/0.0.26/frontend-plugin-core-0.0.26.jar): No plugin descriptor found at META-INF/maven/plugin.xml
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.extractPluginDescriptor(DefaultMavenPluginManager.java:239)
...

Caused by: java.io.IOException: No plugin descriptor found at META-INF/maven/plugin.xml
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.extractPluginDescriptor(DefaultMavenPluginManager.java:234)
	... 26 more
```

Other Details:

```
$ mvn --version

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: <some folder>/apache-maven-3.3.9
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.31-2.b13.el7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-229.el7.x86_64", arch: "amd64", family: "unix"
```

**Comment by eirslett** [comment]
You're using this:
```
<artifactId>frontend-plugin-core</artifactId>
```

but should be using this:
```
<artifactId>frontend-maven-plugin</artifactId>
```

**Comment by shaiksphere** [comment]
Thank you for the prompt response. My bad.
