### ISSUE TITLE
unable to execute frontend:karma as individual goal

### ISSUE THREAD

**Issue by jgangemi** [eirslett/frontend-maven-plugin#365]
trying to run the `frontend:karma` goal by itself throws an exception from the plugin, here's the stacktrace:

```
[INFO] Running 'karma start karma.conf.js --no-colors' in /Users/jgangemi/projects/conductor/conductor/projects/com.conductor.web.analytics/src/main/webapp
[INFO] 16 02 2016 18:55:36.803:ERROR [config]: File /Users/jgangemi/projects/conductor/conductor/projects/com.conductor.web.analytics/src/main/webapp/karma.conf.js does not exist!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.851 s
[INFO] Finished at: 2016-02-16T18:55:36-05:00
[INFO] Final Memory: 24M/981M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:karma (default-cli) on project com.conductor.web.analytics: Failed to run task: 'karma start karma.conf.js --no-colors' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:karma (default-cli) on project com.conductor.web.analytics: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:69)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'karma start karma.conf.js --no-colors' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:59)
	at com.github.eirslett.maven.plugins.frontend.mojo.KarmaRunMojo.execute(KarmaRunMojo.java:40)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:67)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
and the relevant bits of the config:
```xml
          <execution>
            <id>javascript tests</id>
            <goals>
              <goal>karma</goal>
            </goals>
            <phase>test</phase>
            <configuration>
              <karmaConfPath>${project.basedir}/karma.conf.js</karmaConfPath>
              <skip>${skip.karma.tests}</skip>
              <skipTests>${skip.karma.tests}</skipTests>
            </configuration>
          </execution>
```
and the `workingdir` is `src/main/webapp` which is configured at the top level.

please let me know what other info you need, thanks!!

**Comment by eirslett** [comment]
There's a message like this in the log output:

[INFO] 16 02 2016 18:55:36.803:ERROR [config]: File /Users/jgangemi/projects/conductor/conductor/projects/com.conductor.web.analytics/src/main/webapp/karma.conf.js does not exist!

Does that file exist? Maybe it's in the wrong folder?

**Comment by jgangemi** [comment]
it exists and the project builds just fine when the plugin is executed via a lifecycle goal (`mvn package`). this only happens if i try to execute the `frontend:karma` goal directly.

**Comment by eirslett** [comment]
Try "mvn test" instead? (Although that would run Java tests as well)

**Comment by jgangemi** [comment]
yes - that's my current work around but i'd like to be able to run `frontend:karma` by itself, hence the reason i'm filing this bug.

**Comment by eirslett** [comment]
Try moving the stuff in `<configuration>` (especially karmaConfPath) out from `<execution><configuration>...` and into `<plugin><configuration>...`? The problem might be that when you run the plugin directly, it doesn't pick up the configuration which is specific for a given execution.

**Comment by xfh** [comment]
I just run into this problem as well. Beeing able to run the plugin directly would be very nice. Is this a Maven issue?
My current workaround is to use Maven profiles to separate executions (for instance the build executions and the e2e executions)

**Comment by eirslett** [comment]
You should copy-paste the helper scripts for karma into your working directory.
Then you can do ./karma start (or just karma start on windows)

**Comment by xfh** [comment]
Actually, my specific problem is about running protractor. I don't mind running karma in a normal during a standard grunt build task using `mvn clean install`.
My motivation to use your plugin lies in an easier continuous integration setup: because it allows me to configure the required NodeJS & NPM version in a very simple way.

I do have various CI jobs like building and deploying to Nexus. But I do also run protractor end-to-end tests on a regular basis. For the latter it suffices to run a single grunt task to start protractor with the right configuration. So in the end it all comes down to the same issue as @jgangemi's: to configure a plugin execution with a specific configuration and to run just that execution.

I can confirm that when moving the configuration block to the top level, the plugin does apply the configuration when running a goal directly. Unfortunately, it does ignore <execution> specific configuration when started directly.

**Comment by jgangemi** [comment]
yeah, now that i think about it, this behavior is just how maven works. `configuration` declared in the `execution` block is only picked up when the goal runs during a `lifecycle` phase.

**Comment by eirslett** [comment]
Yes, unfortunately, this is how Maven works. It might be possible to hack something together with a maven profile, `mvn frontend:karma -PkarmaDirectly`, but I recommend using the helper scripts to trigger protractor. (Possibly via gulp, if you need a more powerful runner)
