### ISSUE TITLE
Spaces in working directory cause issues

### ISSUE THREAD

**Issue by alanager** [eirslett/frontend-maven-plugin#38]
If you have spaces in the working directory of your project, IE:

C:\Application Development\foo\bar\project

Node.js will fail to detect that it has already been installed and will always download and install.  Also, npm install will fail with the following message:

[INFO] Running 'npm install --color=false' in C:\Application Development\foo\bar\project
[INFO] The filename, directory name, or volume label syntax is incorrect.

**Comment by naymesh** [comment]
Had the same issue in one of our builds with spaces (and a dash) in Jenkins workspace directory. Updating *frontend-maven-plugin* plugin version to 0.0.17 which removed the `readlink extra operand` message. 

Unfortunately other errors still remained. Same project built on same Jenkins server without any spaces in workspace directory name builds without error. So this still points to some issues with spaces in directory names. But it could be an issue with other node plugins and not the frontend-maven-plugin. Not sure.

```
[INFO] --- frontend-maven-plugin:0.0.17:install-node-and-npm (install node and npm) @ ibpworkbench ---
[INFO] Downloading: http://repo.maven.apache.org/maven2/com/github/eirslett/frontend-plugin-core/0.0.17/frontend-plugin-core-0.0.17.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/com/github/eirslett/frontend-plugin-core/0.0.17/frontend-plugin-core-0.0.17.pom (2 KB at 16.8 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/com/github/eirslett/frontend-plugin-core/0.0.17/frontend-plugin-core-0.0.17.jar
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar (262 KB at 5338.3 KB/sec)
[INFO] Downloaded: http://repo.maven.apache.org/maven2/com/github/eirslett/frontend-plugin-core/0.0.17/frontend-plugin-core-0.0.17.jar (38 KB at 402.6 KB/sec)
[INFO] Node v0.10.33 is already installed.
[INFO] Found NPM version 2.1.7
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.17:npm (npm install) @ ibpworkbench ---
[INFO] Running 'npm install --color=false' in /home/build/opt/jenkins/jobs/MERGED - IBPWorkbench/workspace/src/main/web
[INFO] npm WARN package.json path@0.4.10 path is also the name of a node core module.
[INFO] 
[INFO] > node-sass@1.2.3 install /home/build/opt/jenkins/jobs/MERGED - IBPWorkbench/workspace/src/main/web/node_modules/gulp-sass/node_modules/node-sass
[INFO] > node scripts/install.js
[INFO] 
[INFO] Binary downloaded and installed at /home/build/opt/jenkins/jobs/MERGED - IBPWorkbench/workspace/src/main/web/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node
[INFO] 
[INFO] > node-sass@1.2.3 postinstall /home/build/opt/jenkins/jobs/MERGED - IBPWorkbench/workspace/src/main/web/node_modules/gulp-sass/node_modules/node-sass
[INFO] > node scripts/build.js
[INFO] 
[INFO] `linux-x64` exists; testing
[INFO] 
[INFO] module.js:356
[INFO]   Module._extensions[extension](this, filename);
[INFO]                                ^
[INFO] Error: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /home/build/opt/jenkins/jobs/MERGED - IBPWorkbench/workspace/src/main/web/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node)
[INFO]     at Module.load (module.js:356:32)
[INFO]     at Function.Module._load (module.js:312:12)
[INFO]     at Module.require (module.js:364:17)
[INFO]     at require (module.js:380:17)
[INFO]     at Object.<anonymous> (/home/build/opt/jenkins/jobs/MERGED - IBPWorkbench/workspace/src/main/web/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:181:15)
[INFO]     at Module._compile (module.js:456:26)
[INFO]     at Object.Module._extensions..js (module.js:474:10)
[INFO]     at Module.load (module.js:356:32)
[INFO]     at Function.Module._load (module.js:312:12)
[INFO]     at Module.require (module.js:364:17)
[INFO] npm ERR! Linux 2.6.32-358.14.1.el6.x86_64
[INFO] npm ERR! argv "/home/build/opt/jenkins/jobs/MERGED - IBPWorkbench/workspace/src/main/web/node/node" "/home/build/opt/jenkins/jobs/MERGED - IBPWorkbench/workspace/src/main/web/node/npm/bin/npm-cli.js" "install" "--color=false"
[INFO] npm ERR! node v0.10.33
[INFO] npm ERR! npm  v2.1.7
[INFO] npm ERR! code ELIFECYCLE
[INFO] 
[INFO] npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
[INFO] npm ERR! Exit status 8
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the node-sass@1.2.3 postinstall script.
[INFO] npm ERR! This is most likely a problem with the node-sass package,
[INFO] npm ERR! not with npm itself.
[INFO] npm ERR! Tell the author that this fails on your system:
[INFO] npm ERR!     node scripts/build.js
[INFO] npm ERR! You can get their info via:
[INFO] npm ERR!     npm owner ls node-sass
[INFO] npm ERR! There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! Please include the following file with any support request:
[INFO] npm ERR!     /home/build/opt/jenkins/jobs/MERGED - IBPWorkbench/workspace/src/main/web/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by eirslett** [comment]
The example project of this maven plugin also functions as a runnable integration test. The folder "frontend-maven-plugin/src/main/it/example project" intentionally has a space in it, in order to trigger such a build failure - in case there is a problem with spaces in the paths.
If you look at the Linux build, it is run on a Jenkins box from CloudBees. It works, so I believe the problem has to be some combination of this plugin and some npm module.

Maybe you could isolate which npm module might be the problem? What happens if you log in to your Jenkins server, mkdir 'test dir with space', cd 'test dir with space', npm install node-sass?
