### ISSUE TITLE
Gulp is not working with frontend-maven-plugin

### ISSUE THREAD

**Issue by M-Aslam** [eirslett/frontend-maven-plugin#405]
**Error:**

> Failed to run task (com.github.eirslett:frontend-maven-plugin:1.0:gulp:gulp:generate-resources)
> 
> org.apache.maven.plugin.MojoFailureException: Failed to run task
> 	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
> 	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
> 	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
> 	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
> 	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
> 	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
> 	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
> Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'gulp.js browserify' failed. (error code 1)
> 	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
> 	at com.github.eirslett.maven.plugins.frontend.mojo.GulpMojo.execute(GulpMojo.java:64)
> 	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
> 	... 32 more

**POM.xml build part:**

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			
			 <plugin>
		        <groupId>com.github.eirslett</groupId>
		        <artifactId>frontend-maven-plugin</artifactId>
		        
		        <version>1.0</version>
		        
				<executions>
		        	        
					<execution>
					    <id>install node and npm</id>
					    <goals>
					        <goal>install-node-and-npm</goal>
					    </goals>
					    <configuration>
					        <nodeVersion>v5.3.0</nodeVersion>
					        <npmVersion>3.3.12</npmVersion>
					    </configuration>
					</execution>
	                    	        	        
			        <execution>
					    <id>npm install</id>
					    <goals>
					        <goal>npm</goal>
					    </goals>
					    <configuration>
					        <arguments>install</arguments>
		
					    </configuration>
					</execution>
				
					<execution>
					    <id>gulp</id>
					    <goals>
					        <goal>gulp</goal>
					    </goals>			
					    <configuration>
					        <arguments>browserify</arguments>
					    </configuration>
					</execution>
				</executions>
		                
	    	</plugin>
		</plugins>
	</build>

**Comment by eirslett** [comment]
This is most probably due to your gulp build failing. Have you tried running "gulp browserify" directly?

**Comment by M-Aslam** [comment]
Yes it's working directly in cli-mode.

**Comment by M-Aslam** [comment]
Any hint?

**Comment by eirslett** [comment]
No, unfortunately not... can you try to make a "test project" with just the minimal amount of code needed to reproduce the problem?

**Comment by M-Aslam** [comment]
Yes sure. I will try soon.

**Comment by hethcox** [comment]
Hi Eirik. I'm having the same issue trying to invoke gulp with a specific task. Here's a snipped from my pom:
