### ISSUE TITLE
plugin fails to download node resources behind a corporate proxy

### ISSUE THREAD

**Issue by bertramn** [eirslett/frontend-maven-plugin#430]
Hi there,

I tried to build a project that makes use of your maven plugin. My pc is behind a corporate firewall which is gernerally not an issue as both my environment variables and also the settings.xml file are configured with the proxy information. Any other maven initiated download from the public web works but your plugin seems to fail downloading node resources.

I can see some log entry about a proxy but the SSL negotiation fails as it tries to connect via the proxy. I think that albeit the protocol for the proxy is set to `http` it may use `https` to connect via the proxy, at least thats what the SSL trace suggests in the below trace.

```
0000: 48 54 54 50 2F                                     HTTP/
main, handling exception: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
```
Proxy configuration I use in the settings.xml file:
```xml
<proxy>
  <id>http</id>
  <active>true</active>
  <protocol>http</protocol>
  <host>proxy</host>
  <port>8080</port>
  <nonProxyHosts>localhost</nonProxyHosts>
  <username>fred</username>
  <password>secret</password>
</proxy>
<proxy>
  <id>https</id>
  <active>true</active>
  <protocol>https</protocol>
  <host>proxy</host>
  <port>8080</port>
  <nonProxyHosts>localhost</nonProxyHosts>
  <username>fred</username>
  <password>secret</password>
</proxy>
```

As said before, I never had any issues with maven behind the proxy and used many different plugins that pull either maven resources or just download files from the web.

Maven Version:

```sh
mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T02:41:47+10:00)
Maven home: C:\dev\apps\maven\apache-maven-3.3.9
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_92\jre
Default locale: en_AU, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

Maven Trace Log:

```
[INFO] --- frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) @ apiman-manager-ui-war ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=1, ConflictMarker.nodeCount=36, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=30, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2, ConflictResolver.conflictItemCount=35, DefaultDependencyCollector.collectTime=270, DefaultDependencyCollector.transformTime=3}
[DEBUG] com.github.eirslett:frontend-maven-plugin:jar:0.0.27:
[DEBUG]    com.github.eirslett:frontend-plugin-core:jar:0.0.27:compile
[DEBUG]       org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[DEBUG]          org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[DEBUG]       org.apache.commons:commons-compress:jar:1.5:compile
[DEBUG]          org.tukaani:xz:jar:1.2:compile
[DEBUG]       commons-io:commons-io:jar:1.3.2:compile
[DEBUG]       org.apache.httpcomponents:httpclient:jar:4.5.1:compile
[DEBUG]          org.apache.httpcomponents:httpcore:jar:4.4.3:compile
[DEBUG]          commons-logging:commons-logging:jar:1.2:compile
[DEBUG]          commons-codec:commons-codec:jar:1.9:compile
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.5:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.1.0:compile
[DEBUG]       org.apache.maven:maven-model:jar:3.1.0:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:3.1.0:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M2a:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]             javax.inject:javax.inject:jar:1:compile
[DEBUG]          com.google.guava:guava:jar:10.0.1:compile
[DEBUG]             com.google.code.findbugs:jsr305:jar:1.3.9:compile
[DEBUG]          org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
[DEBUG]             aopalliance:aopalliance:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M2a:compile
[DEBUG]             asm:asm:jar:3.3.1:compile
[DEBUG]          org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]          org.codehaus.plexus:plexus-classworlds:jar:2.4:compile
[DEBUG]    org.apache.maven.plugin-tools:maven-plugin-annotations:jar:3.2:compile
[DEBUG]    org.sonatype.plexus:plexus-build-api:jar:0.0.7:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.5.8:compile
[DEBUG] Created new class realm plugin>com.github.eirslett:frontend-maven-plugin:0.0.27
[DEBUG] Importing foreign packages into class realm plugin>com.github.eirslett:frontend-maven-plugin:0.0.27
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>com.github.eirslett:frontend-maven-plugin:0.0.27
[DEBUG]   Included: com.github.eirslett:frontend-maven-plugin:jar:0.0.27
[DEBUG]   Included: com.github.eirslett:frontend-plugin-core:jar:0.0.27
[DEBUG]   Included: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13
[DEBUG]   Included: org.codehaus.jackson:jackson-core-asl:jar:1.9.13
[DEBUG]   Included: org.apache.commons:commons-compress:jar:1.5
[DEBUG]   Included: org.tukaani:xz:jar:1.2
[DEBUG]   Included: commons-io:commons-io:jar:1.3.2
[DEBUG]   Included: org.apache.httpcomponents:httpclient:jar:4.5.1
[DEBUG]   Included: org.apache.httpcomponents:httpcore:jar:4.4.3
[DEBUG]   Included: commons-logging:commons-logging:jar:1.2
[DEBUG]   Included: commons-codec:commons-codec:jar:1.9
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: javax.annotation:jsr250-api:jar:1.0
[DEBUG]   Included: com.google.guava:guava:jar:10.0.1
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:1.3.9
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M2a
[DEBUG]   Included: asm:asm:jar:3.3.1
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.apache.maven.plugin-tools:maven-plugin-annotations:jar:3.2
[DEBUG]   Included: org.sonatype.plexus:plexus-build-api:jar:0.0.7
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.5.8
[DEBUG] Configuring mojo com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm from plugin realm ClassRealm[plugin>com.github.eirslett:frontend-maven-plugin:0.0.27, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm' with basic configurator -->
[DEBUG]   (f) nodeDownloadRoot = https://nodejs.org/dist/
[DEBUG]   (f) nodeVersion = v5.6.0
[DEBUG]   (f) npmDownloadRoot = http://registry.npmjs.org/npm/-/
[DEBUG]   (f) npmVersion = 3.6.0
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@6e0c6a7a
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipTests = false
[DEBUG]   (f) workingDirectory = C:\Users\fred\workspaces\api\apiman\manager\ui\war
[DEBUG]   (f) execution = com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm {execution: install node and npm}
[DEBUG] -- end configuration --
[INFO] Found proxies: [http{protocol='http', host='proxy', port=8080, with username/passport authentication}, https{protocol='https', host='proxy', port=8080, with username/passport authentication}]
[INFO] Installing node version v5.6.0
[INFO] Downloading via proxy https{protocol='https', host='proxy', port=8080, with username/passport authentication}
trustStore is: C:\Program Files\Java\jdk1.8.0_92\jre\lib\security\cacerts
trustStore type is : jks
trustStore provider is :
init truststore
adding as trusted cert:
  Subject: CN=Equifax Secure Global eBusiness CA-1, O=Equifax Secure Inc., C=US
  Issuer:  CN=Equifax Secure Global eBusiness CA-1, O=Equifax Secure Inc., C=US
  Algorithm: RSA; Serial number: 0xc3517
  Valid from Mon Jun 21 14:00:00 AEST 1999 until Mon Jun 22 14:00:00 AEST 2020
...
trigger seeding of SecureRandom
done seeding SecureRandom
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1.1
%% No cached client session
*** ClientHello, TLSv1.2
RandomCookie:  GMT: 1464935703 bytes = { 220, 44, 23, 188, 180, 39, 73, 31, 82, 245, 26, 170, 55, 202, 119, 147, 175, 88, 20, 30, 8, 255, 109, 147, 202, 88, 138, 108 }
Session ID:  {}
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, sect163k1, sect163r2, secp192r1, secp224r1, sect233k1, sect233r1, sect283k1, sect283r1, secp384r1, sect409k1, sect409r1, secp521r1, sect571k1, sect571r1, secp160k1, secp160r1, secp160r2, sect163r1, secp192k1, sect193r1, sect193r2, secp224k1, sect239k1, secp256k1}
Extension ec_point_formats, formats: [uncompressed]
Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
Extension server_name, server_name: [type=host_name (0), value=proxy]
***
...
[Raw read]: length = 5
0000: 48 54 54 50 2F                                     HTTP/
main, handling exception: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
main, SEND TLSv1.2 ALERT:  fatal, description = unexpected_message
main, WRITE: TLSv1.2 Alert, length = 2
[Raw write]: length = 7
0000: 15 03 03 00 02 02 0A                               .......
main, called closeSocket()
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] apiman-manager-ui-war .............................. FAILURE [  2.502 s]
[INFO] apiman-manager-ui-war-wildfly8 ..................... SKIPPED
[INFO] apiman-gateway-engine-ispn ......................... SKIPPED
[INFO] apiman-gateway-engine-es ........................... SKIPPED
[INFO] apiman-gateway-engine-hawkular ..................... SKIPPED
[INFO] apiman-gateway-engine-jdbc ......................... SKIPPED
[INFO] apiman-gateway-engine-influxdb ..................... SKIPPED
[INFO] apiman-test-policies ............................... SKIPPED
[INFO] apiman-gateway-engine-policies ..................... SKIPPED
[INFO] apiman-gateway-platforms ........................... SKIPPED
[INFO] apiman-gateway-platforms-servlet ................... SKIPPED
[INFO] apiman-gateway-api-rest-impl ....................... SKIPPED
[INFO] apiman-gateway-platforms-war ....................... SKIPPED
[INFO] apiman-gateway-platforms-war-wildfly8 .............. SKIPPED
[INFO] apiman-gateway-platforms-war-wildfly8-api .......... SKIPPED
[INFO] apiman-gateway-platforms-war-wildfly8-gateway ...... SKIPPED
[INFO] apiman-distro-es ................................... SKIPPED
[INFO] apiman-distro-wildfly9 ............................. SKIPPED
[INFO] apiman-distro-wildfly10 ............................ SKIPPED
[INFO] apiman-distro-eap7 ................................. SKIPPED
[INFO] apiman-manager-api-war-tomcat8 ..................... SKIPPED
[INFO] apiman-manager-ui-war-tomcat8 ...................... SKIPPED
[INFO] apiman-gateway-platforms-war-tomcat8 ............... SKIPPED
[INFO] apiman-gateway-platforms-war-tomcat8-api ........... SKIPPED
[INFO] apiman-gateway-platforms-war-tomcat8-gateway ....... SKIPPED
[INFO] apiman-distro-tomcat8 .............................. SKIPPED
[INFO] apiman-distro-wildfly8 ............................. SKIPPED
[INFO] apiman-manager-api-micro ........................... SKIPPED
[INFO] apiman-manager-test ................................ SKIPPED
[INFO] apiman-manager-test-api ............................ SKIPPED
[INFO] apiman-gateway-engine-osgi ......................... SKIPPED
[INFO] apiman-gateway-engine-prometheus ................... SKIPPED
[INFO] apiman-gateway-platforms-vertx3-common ............. SKIPPED
[INFO] apiman-gateway-engine-vertx-eb-inmemory ............ SKIPPED
[INFO] apiman-gateway-platforms-war-micro ................. SKIPPED
[INFO] apiman-gateway-platforms-vertx3 .................... SKIPPED
[INFO] apiman-gateway-test ................................ SKIPPED
[INFO] apiman-test-suite .................................. SKIPPED
[INFO] apiman-tools ....................................... SKIPPED
[INFO] apiman-tools-ddl ................................... SKIPPED
[INFO] apiman-tools-i18n .................................. SKIPPED
[INFO] apiman-tools-jdbc .................................. SKIPPED
[INFO] apiman-tools-ldap .................................. SKIPPED
[INFO] apiman-tools-services .............................. SKIPPED
[INFO] apiman-tools-server-all ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.875 s
[INFO] Finished at: 2016-06-03T16:35:03+10:00
[INFO] Final Memory: 61M/466M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) on project apiman-manager-ui-war: Could not download Node.js from: https://nodejs.org/dist/v5.6.0/win-x64/node.exe: Could not download https://nodejs.org/dist/v5.6.0/win-x64/node.exe: Unrecognized SSL message, plaintext connection? -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) on project apiman-manager-ui-war: Could not download Node.js from: https://nodejs.org/dist/v5.6.0/win-x64/node.exe: Could not download https://nodejs.org/dist/v5.6.0/win-x64/node.exe
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Could not download Node.js from: https://nodejs.org/dist/v5.6.0/win-x64/node.exe: Could not download https://nodejs.org/dist/v5.6.0/win-x64/node.exe
        at com.github.eirslett.maven.plugins.frontend.mojo.MojoUtils.toMojoFailureException(MojoUtils.java:20)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:71)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.InstallationException: Could not download Node.js from: https://nodejs.org/dist/v5.6.0/win-x64/node.exe
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller$NodeAndNPMInstallAction.installNodeForWindows(NodeAndNPMInstaller.java:239)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller$NodeAndNPMInstallAction.install(NodeAndNPMInstaller.java:65)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller.install(NodeAndNPMInstaller.java:44)
        at com.github.eirslett.maven.plugins.frontend.mojo.InstallNodeAndNpmMojo.execute(InstallNodeAndNpmMojo.java:78)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:67)
        ... 22 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.DownloadException: Could not download https://nodejs.org/dist/v5.6.0/win-x64/node.exe
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultFileDownloader.download(FileDownloader.java:71)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller$NodeAndNPMInstallAction.downloadFile(NodeAndNPMInstaller.java:249)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInstaller$NodeAndNPMInstallAction.installNodeForWindows(NodeAndNPMInstaller.java:236)
        ... 26 more
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
        at sun.security.ssl.InputRecord.read(InputRecord.java:527)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:388)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultFileDownloader.executeViaProxy(FileDownloader.java:111)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultFileDownloader.execute(FileDownloader.java:83)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultFileDownloader.download(FileDownloader.java:59)
        ... 28 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Finalizer, called close()
Finalizer, called closeInternal(true)
```

**Comment by pablogrs** [comment]
have you set it like this? I think you might have a problem in your settings, mines are working perfectly.
```
<settings>
  <proxies>
    <proxy>
      <active>true</active>
      <protocol>http</protocol>
      <host>your.web-proxy.com</host>
      <port>8080</port>
      <nonProxyHosts>*.internal</nonProxyHosts>
  </proxy>
</proxies>
...
```
