### ISSUE TITLE
npm install suddenly failing

### ISSUE THREAD

**Issue by jaranflaath** [eirslett/frontend-maven-plugin#456]
We recently upgraded to Jenkins 2.0 and after that npm install suddenly fails. There were one successful build on 2.0, before it started to fail. 

```
[INFO] --- frontend-maven-plugin:1.0:npm (npm) @ boks-interfaces-web ---
[INFO] Running 'npm install' in /u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/src/main/resources/webapp/admin
[ERROR] npm ERR! Linux 2.6.32-642.3.1.el6.x86_64
[ERROR] npm ERR! argv "/u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/target/node/node" "/u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/target/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v4.4.7
[ERROR] npm ERR! npm  v3.10.6
[ERROR] 
[ERROR] npm ERR! Cannot convert undefined or null to object
[ERROR] npm ERR! 
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/src/main/resources/webapp/admin/npm-debug.log
```

Here is the output from npm-debug.log: 

```
3022 verbose get saving regenerator-runtime to /home/jenkinsnode/.npm/aurora/nexus/content/groups/npm-all/regenerator-runtime/.cache.json
3023 verbose correctMkdir /home/jenkinsnode/.npm correctMkdir not in flight; initializing
3024 verbose stack TypeError: Cannot convert undefined or null to object
3024 verbose stack     at Function.keys (native)
3024 verbose stack     at pickVersionFromRegistryDocument (/u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/target/node/node_modules/npm/lib/fetch-package-metadata.js:125:29)
3024 verbose stack     at /u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/target/node/node_modules/npm/node_modules/iferr/index.js:13:50
3024 verbose stack     at /u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/target/node/node_modules/npm/lib/utils/pulse-till-done.js:20:8
3024 verbose stack     at saved (/u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/target/node/node_modules/npm/lib/cache/caching-client.js:174:7)
3024 verbose stack     at /u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/target/node/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
3024 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
3025 verbose cwd /u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/src/main/resources/webapp/admin
3026 error Linux 2.6.32-642.3.1.el6.x86_64
3027 error argv "/u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/target/node/node" "/u01/jenkins_buildnode/workspace/boks-systemverifikasjon/boks-interfaces-web/target/node/node_modules/npm/bin/npm-cli.js" "install"
3028 error node v4.4.7
3029 error npm  v3.10.6
3030 error Cannot convert undefined or null to object
3031 error If you need help, you may report this error at:
3031 error     <https://github.com/npm/npm/issues>
3032 verbose exit [ 1, true ]
```

Plugin configuration:

```
<plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <configuration>
          <workingDirectory>src/main/resources/webapp/admin</workingDirectory>
          <installDirectory>target</installDirectory>
          <nodeVersion>v4.4.7</nodeVersion>
          <npmVersion>3.10.6</npmVersion>
        </configuration>
        <executions>
          <execution>
            <id>npm install</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <phase>${npm.build.phase}</phase>
          </execution>
          <execution>
            <id>npm</id>
            <goals>
              <goal>npm</goal>
            </goals>
            <phase>${npm.build.phase}</phase>
            <configuration>
              <arguments>install</arguments>
              <workingDirectory>src/main/resources/webapp/admin</workingDirectory>
              <installDirectory>target</installDirectory>
            </configuration>
          </execution>
          <execution>
            <id>webpack</id>
            <goals>
              <goal>webpack</goal>
            </goals>
            <phase>${npm.build.phase}</phase>
          </execution>
        </executions>
      </plugin>
```

I have tried different versions of npm, but to no effect. The error messages are rather cryptic, so hoping for some help here. 

The node.build.phase property is set to "none" by default and to "deploy" by the only module in our project that should be built with npm.

Thanks in advance! :)

**Comment by nugent** [comment]
Are you using a node proxy ?

**Comment by jaranflaath** [comment]
Thanks for the tip, @nugent. We are in fact using a npm proxy, so that might very well have been the problem. Need to revisit this when I pick up work on this part of the application again.

**Comment by eirslett** [comment]
I'll close for now. Reopen if needed!
