### ISSUE TITLE
Unable to execute karma test

### ISSUE THREAD

**Issue by dfoulkes** [eirslett/frontend-maven-plugin#460]
**WHEN** 
running mvn clean install ,
executing: karma start src/test/javascript/karma.conf.ci.js'

**THEN**

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.1-SNAPSHOT:karma (javascript tests) on project example: Failed to run task: 'karma start src/test/javascript/karma.conf.ci.js' failed. (error code 1) -> [Help 1]
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.1-SNAPSHOT:karma (javascript tests) on project example: Failed to run task
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[INFO]  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
[INFO]  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
[INFO]  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[INFO]  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
[INFO]  at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:483)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
[INFO]  at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
[INFO]  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[INFO]  ... 19 more
[INFO] Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'karma start src/test/javascript/karma.conf.ci.js' failed. (error code 1)
[INFO]  at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
[INFO]  at com.github.eirslett.maven.plugins.frontend.mojo.KarmaRunMojo.execute(KarmaRunMojo.java:40)
[INFO]  at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
[INFO]  ... 21 more
[INFO] [ERROR] 
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[INFO] ..FAILED (81.7 s)
[INFO]   The build exited with code 1. See /Users/danfoulkes/Library/Mobile Documents/com~apple~CloudDocs/Workspace/prometheus/frontend-maven-plugin/frontend-maven-plugin/target/it/example project/build.log for details.
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 2, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  example project/pom.xml
[INFO] -------------------------------------------------

**Comment by dfoulkes** [comment]
[INFO] [INFO] 04 09 2016 13:59:18.597:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
[INFO] [INFO] 04 09 2016 13:59:18.604:INFO [launcher]: Starting browser PhantomJS
[INFO] [INFO] 04 09 2016 13:59:18.710:ERROR [launcher]: Cannot start PhantomJS
[INFO] [INFO]   
[INFO] [INFO] 04 09 2016 13:59:18.714:INFO [launcher]: Trying to start PhantomJS again (1/2).
[INFO] [INFO] 04 09 2016 13:59:18.815:ERROR [launcher]: Cannot start PhantomJS
[INFO] [INFO]   
[INFO] [INFO] 04 09 2016 13:59:18.816:INFO [launcher]: Trying to start PhantomJS again (2/2).
[INFO] [INFO] 04 09 2016 13:59:18.914:ERROR [launcher]: Cannot start PhantomJS
[INFO] [INFO]   
[INFO] [INFO] 04 09 2016 13:59:18.915:ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
[INFO] [INFO] ------------------------------------------------------------------------

**Comment by dfoulkes** [comment]
installing the following on my system node.js resolved the problem however kinda goes against what this plugin is suppose to achieve.

npm install phantomjs -g
npm -g karma-phantomjs-launcher
npm install karma-phantomjs-launcher -g
npm install karma-jasmine -g
