### ISSUE TITLE
Broken bower install?

### ISSUE THREAD

**Issue by tykeal** [eirslett/frontend-maven-plugin#461]
I'm trying to add in use of this plugin for a project but am having issues with bower. I see that Issue #350 has been closed but I can't seem to get bower to install.

My current configuration looks like this

```xml
<plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>1.0</version>
        <executions>
                <execution>
                        <id>install node and npm</id>
                        <goals>
                                <goal>install-node-and-npm</goal>
                        </goals>
                </execution>
                <execution>
                        <id>npm install</id>
                        <goals>
                                <goal>npm</goal>
                        </goals>
                </execution>
                <execution>
                        <id>bower install</id>
                        <goals>
                                <goal>bower</goal>
                        </goals>
                </execution>
        </executions>
        <configuration>
                <nodeVersion>v4.5.0</nodeVersion>
                <npmVersion>3.10.6</npmVersion>
        </configuration>
</plugin>
```

And I'm getting the following error:

```
[INFO] --- frontend-maven-plugin:1.0:npm (npm) @ winery ---
[INFO] Running 'npm install' in /w/workspace/thirdparty-winery
[WARNING] npm WARN enoent ENOENT: no such file or directory, open '/w/workspace/thirdparty-winery/package.json'
[WARNING] npm WARN thirdparty-winery No description
[WARNING] npm WARN thirdparty-winery No repository field.
[WARNING] npm WARN thirdparty-winery No README data
[WARNING] npm WARN thirdparty-winery No license field.
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:bower (bower) @ winery ---
[INFO] Running 'bower install' in /w/workspace/thirdparty-winery
[ERROR] module.js:327
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module '/w/workspace/thirdparty-winery/node_modules/bower/bin/bower'
[ERROR]     at Function.Module._resolveFilename (module.js:325:15)
[ERROR]     at Function.Module._load (module.js:276:25)
[ERROR]     at Function.Module.runMain (module.js:441:10)
[ERROR]     at startup (node.js:139:18)
[ERROR]     at node.js:974:3
```

Which looks like the error from #350. I saw reference to using bower 1.7.2 in #350, how do I go about forcing that to install instead of the latest version?

**Comment by eirslett** [comment]
I suggest that you run bower through an npm script, with the npm mojo, instead of using the bower one directly. Bower probably changed the way it is bootstrapped, so that it doesn't work with this plugin any longer.
