### ISSUE TITLE
NPE during

### ISSUE THREAD

**Issue by mriehema** [eirslett/frontend-maven-plugin#513]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

```
[INFO] --- frontend-maven-plugin:1.2:install-node-and-npm (install-node-and-npm) @ am-theme ---
[INFO] Node v4.6.0 was installed, but we need version v6.9.1
[INFO] Installing node version v6.9.1
[INFO] Unpacking C:\Users\mriehema\.m2\repository\com\github\eirslett\node\6.9.1\node-6.9.1-win-x64.zip into C:\dev\node\tmp
[INFO] Copying node binary from C:\dev\node\tmp\node-v6.9.1-win-x64\node.exe to C:\dev\node\node.exe
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 min
[INFO] Finished at: 2016-11-15T15:57:03+01:00
[INFO] Final Memory: 560M/1470M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:install-node-and-npm (install-node-and-npm) on project am-theme: Execution install-node-and-npm of goal com.github.eirslett:frontend-maven-plugin:1.2:install-node-and-npm failed. NullPointerException -> [Help 1]
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- Install node 4.x via frontend-maven-plugin
- Change version in pom.xml to 6.91
- Run mvn install again

**What is the expected behavior?**

The old one should be replaced.

**Please mention your frontend-maven-plugin and operating system version.**

- Win7, x64
- frontend-maven-plugin 1.2
- JDK8
- Maven 3.3.9

Old Config:
        <plugin>
          <groupId>com.github.eirslett</groupId>
          <artifactId>frontend-maven-plugin</artifactId>
          <version>1.1</version>
          <configuration>
            <nodeVersion>v4.6.0</nodeVersion> 
            <npmVersion>3.10.8</npmVersion>
          </configuration>
        </plugin>

New config:
```
        <plugin>
          <groupId>com.github.eirslett</groupId>
          <artifactId>frontend-maven-plugin</artifactId>
          <version>1.2</version>
          <configuration>
            <nodeVersion>v6.9.1</nodeVersion><!-- LTS -->
            <!-- use bundled npm -->
          </configuration>
            <executions>
              <execution>
                <id>install-node-and-npm</id>
                <goals>
                  <goal>install-node-and-npm</goal>
                </goals>
              </execution>
              </execution>
        </plugin>
```

**Comment by mriehema** [comment]
Stacktrace:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:install-node-and-npm (install-node-and-npm) on project am-theme: Execution install-node-and-npm of goal com.github.eirslett:frontend-maven-plugin:1.2:install-node-and-npm failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution install-node-and-npm of goal com.github.eirslett:frontend-maven-plugin:1.2:install-node-and-npm failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at com.github.eirslett.maven.plugins.frontend.mojo.MojoUtils.toMojoFailureException(MojoUtils.java:27)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:97)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

**Comment by mcgivrer** [comment]
I am in front on the same error on Java 1.8.0_25 maven 3.3.9, on Windows 7 64bits.

**Comment by mriehema** [comment]
You can delete the node folder manually as a workaround. But we should fix this.

**Comment by chrisrink** [comment]
This looks like an issue with the File.renameTo() method.

frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/NodeInstaller.java:222


I see a comment in stackoverflow to try File.move()
`
String fileName = "MyFile.txt";

try {
    Files.move(new File(fileName).toPath(), new File(fileName).toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
} catch (IOException ex) {
    Logger.getLogger(SomeClass.class.getName()).log(Level.SEVERE, null, ex);
}
`
https://stackoverflow.com/questions/1000183/reliable-file-renameto-alternative-on-windows.

Not sure if anyone has tried this.

**Comment by GregDomjan** [comment]
Just to say, still an issue, rather than raising a new issue.

After updating
 * frontend-maven-plugin from 1.4 to 1.7.5
 * the nodeVersion from v6.10.2 to v10.15.3

```
[INFO] Node v6.10.2 was installed, but we need version v10.15.3
[INFO] Installing node version v10.15.3
[INFO] Downloading https://nodejs.org/dist/v10.15.3/node-v10.15.3-win-x64.zip to C:\Data\.m2\repository\com\github\eirslett\node\10.15.3\node-10.15.3-win-x64.zip
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] Unpacking C:\Data\.m2\repository\com\github\eirslett\node\10.15.3\node-10.15.3-win-x64.zip into C:\data\iamssoa\iam-singlesignonassistant\Edge\node\tmp
[INFO] Copying node binary from C:\Foo\node\tmp\node-v10.15.3-win-x64\node.exe to C:\Foo\node\node.exe
...
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:install-node-and-npm (install node and npm) on project Foo: Could not install Node: Was not allowed to rename C:\Foo\node\tmp\node-v10.15.3-win-x64\node.exe to C:\Foo\node\node.exe -> [Help 1]
...
Caused by: com.github.eirslett.maven.plugins.frontend.lib.InstallationException: Could not install Node: Was not allowed to rename C:\data\iamssoa\iam-singlesignonassistant\Edge\node\tmp\node-v10.15.3-win-x64\node.exe to C:\data\iamssoa\iam-singlesignonassistant\Edge\node\node.exe
    at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.installNodeWithNpmForWindows (NodeInstaller.java:223)
```

On Windows 10, Maven 3.6.0, Java 1.8.0_71 x64

**Comment by jpierson** [comment]
I ran into this using this issue and was pointed to this issue from https://github.com/eirslett/frontend-maven-plugin/issues/738 after recently attempting to update our project from NodeJS 10 to 12 to follow the latest LTS. Removing the existing `node` sub-folder seemed to work for me as a workaround.
