### ISSUE TITLE
frontend-maven-plugin:1.1:bower (bower install) on project tez-ui: Failed to run task: 'bower install' failed. (error code 1

### ISSUE THREAD

**Issue by Chopinxb** [eirslett/frontend-maven-plugin#521]
when i compile the **Tez** source code in my CentOS 7.2, i configure node v7.1.0 and npm 4. 0. 3,
it comes the error:

[INFO] Node v7.1.0 is already installed.
[INFO] NPM 4.0.3 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.1:npm (npm install) @ tez-ui ---
[INFO] Running 'npm install' in /search/odin/apache-tez/tez-master/tez-ui/src/main/webapp
[INFO] 
[INFO] --- frontend-maven-plugin:1.1:bower (bower install) @ tez-ui ---
[INFO] Running 'bower install' in /search/odin/apache-tez/tez-master/tez-ui/src/main/webapp
**[ERROR] module.js:474
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module 'internal/fs'
[ERROR]     at Function.Module._resolveFilename (module.js:472:15)
[ERROR]     at Function.Module._load (module.js:420:25)
[ERROR]     at Module.require (module.js:500:17)
[ERROR]     at require (internal/module.js:20:19)
[ERROR]     at evalmachine.<anonymous>:17:20
[ERROR]     at Object.<anonymous> (/search/odin/apache-tez/tez-master/tez-ui/src/main/webapp/node_modules/bower/lib/node_modules/graceful-fs/fs.js:11:1)
[ERROR]     at Module._compile (module.js:573:32)
[ERROR]     at Object.Module._extensions..js (module.js:582:10)
[ERROR]     at Module.load (module.js:490:32)
[ERROR]     at tryModuleLoad (module.js:449:12)**
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tez ................................................ SUCCESS [  1.422 s]
[INFO] hadoop-shim ........................................ SUCCESS [06:16 min]
[INFO] tez-api ............................................ SUCCESS [02:08 min]
[INFO] tez-common ......................................... SUCCESS [  0.504 s]
[INFO] tez-runtime-internals .............................. SUCCESS [  0.889 s]
[INFO] tez-runtime-library ................................ SUCCESS [ 17.455 s]
[INFO] tez-mapreduce ...................................... SUCCESS [ 20.544 s]
[INFO] tez-examples ....................................... SUCCESS [  0.280 s]
[INFO] tez-dag ............................................ SUCCESS [ 26.299 s]
[INFO] tez-tests .......................................... SUCCESS [ 24.643 s]
[INFO] tez-ext-service-tests .............................. SUCCESS [  0.778 s]
[INFO] tez-ui ............................................. FAILURE [ 57.580 s]
[INFO] tez-plugins ........................................ SKIPPED
[INFO] tez-yarn-timeline-history .......................... SKIPPED
[INFO] tez-yarn-timeline-history-with-acls ................ SKIPPED
[INFO] tez-history-parser ................................. SKIPPED
[INFO] tez-tools .......................................... SKIPPED
[INFO] tez-perf-analyzer .................................. SKIPPED
[INFO] tez-job-analyzer ................................... SKIPPED
[INFO] tez-javadoc-tools .................................. SKIPPED
[INFO] hadoop-shim-impls .................................. SKIPPED
[INFO] hadoop-shim-2.6 .................................... SKIPPED
[INFO] tez-dist ........................................... SKIPPED
[INFO] Tez ................................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:56 min
[INFO] Finished at: 2016-11-22T16:57:47+08:00
[INFO] Final Memory: 76M/555M
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.1:bower (bower install) on project tez-ui: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tez-ui

please provide any solution for this.

**Comment by tikiwade** [comment]
I am having a similar issue that might be the same thing
[INFO] Running 'bower install' in C:\<project directory>
[ERROR] module.js:471
[ERROR]     throw err;
[ERROR]     ^
[ERROR]
[ERROR] Error: Cannot find module 'C:<project directory>\node_modules\bower\bin\bower'
[ERROR]     at Function.Module._resolveFilename (module.js:469:15)
[ERROR]     at Function.Module._load (module.js:417:25)
[ERROR]     at Module.runMain (module.js:604:10)
[ERROR]     at run (bootstrap_node.js:394:7)
[ERROR]     at startup (bootstrap_node.js:149:9)
[ERROR]     at bootstrap_node.js:509:3
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.741 s
[INFO] Finished at: 2016-12-20T15:15:42-06:00
[INFO] Final Memory: 8M/150M
[INFO] ------------------------------------------------------------------------
