### ISSUE TITLE
install-node-and-yarn throws java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by wardr** [eirslett/frontend-maven-plugin#527]
When I attempt to execute install-node-and-npm or install-node-and-yarn, I get the following stack trace:

```
[WARNING] The POM for com.github.eirslett:frontend-maven-plugin:jar:1.3 is missing, no dependency information available
[INFO] 
[INFO] --- frontend-maven-plugin:1.3:install-node-and-yarn (install node and yarn) @ example-html ---
[WARNING] The POM for com.github.eirslett:frontend-maven-plugin:jar:1.3 is missing, no dependency information available
[WARNING] Error injecting: com.github.eirslett.maven.plugins.frontend.mojo.InstallNodeAndYarnMojo
java.lang.NoClassDefFoundError: com/github/eirslett/maven/plugins/frontend/lib/TaskRunnerException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	[snipped for brevity]
Caused by: java.lang.ClassNotFoundException: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	[snipped for brevity]
```

The relevant portion of the project pom.xml:

```
<plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <version>1.3</version>

    <configuration>
        <installDirectory>bin</installDirectory>
    </configuration>

    <executions>

        <execution>
            <id>install node and yarn</id>
            <goals>
                <goal>install-node-and-yarn</goal>
            </goals>
            <configuration>
                <nodeVersion>v6.9.1</nodeVersion>
                <yarnVersion>v0.17.9</yarnVersion>
            </configuration>
        </execution>

        <execution>
            <id>yarn run build</id>
            <goals>
                <goal>yarn</goal>
            </goals>
            <configuration>
                <arguments>run build</arguments>
            </configuration>
        </execution>

    </executions>

</plugin>
```

Environment: Windows 10, Java 8, Maven 3.2.1

This bug only happens with version 1.3 of frontend-maven-plugin; version 1.2 works correctly.

**Comment by eirslett** [comment]
Try a newer Maven version maybe?

**Comment by wardr** [comment]
That was it, thanks. Worked with Maven 3.3.9
