### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:gulp

### ISSUE THREAD

**Issue by math29** [eirslett/frontend-maven-plugin#536]
Hello everyone,

I would know if somebody already had this kind of error on windows executing a maven clean install : 

`[INFO] --- frontend-maven-plugin:0.0.22:gulp (gulp build) @ aat ---
[DEBUG] Configuring mojo com.github.eirslett:frontend-maven-plugin:0.0.22:gulp from plugin realm ClassRealm[plugin>com.github.eirslett:frontend-maven-plugin:0.0.22, parent: sun.misc.Launcher$AppClassLoader@338bd37a]
[DEBUG] Configuring mojo 'com.github.eirslett:frontend-maven-plugin:0.0.22:gulp' with basic configurator -->
[DEBUG]   (f) arguments = build
[DEBUG]   (f) skip = false
[DEBUG]   (f) triggerfiles = []
[DEBUG]   (f) workingDirectory = C:\Users\mallain\workspace\aat-ui\application
[DEBUG] -- end configuration --
[INFO] Running 'gulp build --no-color' in C:\Users\mallain\workspace\aat-ui\application
[INFO] [13:31:52] Using gulpfile ~\workspace\aat-ui\application\gulpfile.js
[INFO] [13:31:52] Starting 'build'...
[INFO] [13:31:52] Starting 'clean'...
[INFO] [13:31:52] Finished 'clean' after 61 ms
[INFO] [13:31:52] Starting 'wiredep'...
[INFO] [13:31:52] Starting 'eslint'...
[INFO] [13:31:53] Starting 'templateCache'...
[INFO] [13:31:54] Starting 'images-theme-svg'...
[INFO] [13:31:54] Starting 'images-catalogue'...
[INFO] [13:31:55] 'images-catalogue' errored after 1.07 s
[INFO] [13:31:55] C:\Users\mallain\workspace\aat-ui\application\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs\node_modules\gulp-sourcemaps\index.js:38
[INFO]     debug(() => {return options;});
[INFO]            ^
[INFO] SyntaxError: Unexpected token )
[INFO]     at exports.runInThisContext (vm.js:73:16)
[INFO]     at Module._compile (module.js:443:25)
[INFO]     at Object.Module._extensions..js (module.js:478:10)
[INFO]     at Module.load (module.js:355:32)
[INFO]     at Function.Module._load (module.js:310:12)
[INFO]     at Module.require (module.js:365:17)
[INFO]     at require (module.js:384:17)
[INFO]     at Object.<anonymous> (C:\Users\mallain\workspace\aat-ui\application\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs\lib\src\index.js:8:18)
[INFO]     at Module._compile (module.js:460:26)
[INFO]     at Object.Module._extensions..js (module.js:478:10)
[INFO]     at Module.load (module.js:355:32)
[INFO]     at Function.Module._load (module.js:310:12)
[INFO]     at Module.require (module.js:365:17)
[INFO]     at require (module.js:384:17)
[INFO]     at Object.<anonymous> (C:\Users\mallain\workspace\aat-ui\application\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs\index.js:4:8)
[INFO]     at Module._compile (module.js:460:26)
[INFO]     at Object.Module._extensions..js (module.js:478:10)
[INFO]     at Module.load (module.js:355:32)
[INFO]     at Function.Module._load (module.js:310:12)
[INFO]     at Module.require (module.js:365:17)
[INFO]     at require (module.js:384:17)
[INFO]     at Object.<anonymous> (C:\Users\mallain\workspace\aat-ui\application\node_modules\gulp-imagemin\node_modules\imagemin\index.js:7:15)
[INFO] [13:31:55] 'build' errored after 3.24 s
[INFO] [13:31:55] Error in plugin 'run-sequence'
[INFO] Message:
[INFO]     An error occured in task 'images-catalogue'.
[INFO] [13:31:57] Finished 'wiredep' after 5.46 s
[INFO] [13:31:58] all files 34.71 kB
[INFO] [13:31:58] Finished 'images-theme-svg' after 3.89 s
[INFO] [13:31:58] Finished 'templateCache' after 5.07 s
[INFO] [13:31:59] 
... 
[INFO] [13:31:59] Finished 'eslint' after 7.47 s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:52.635s
[INFO] Finished at: Mon Dec 12 13:31:59 CET 2016
[INFO] Final Memory: 11M/154M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:gulp (gulp build) on project aat: Failed to run task: 'gulp build --no-color' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:gulp (gulp build) on project aat: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.GulpMojo.execute(GulpMojo.java:72)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'gulp build --no-color' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:38)
	at com.github.eirslett.maven.plugins.frontend.mojo.GulpMojo.execute(GulpMojo.java:70)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Please mention your frontend-maven-plugin and operating system version.**

I use : 
- nodejs version v4.4.4
- npm version : 2.15.1
- mvn : 
`Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
Maven home: D:\java\apache-maven-3.0.4\bin\..
Java version: 1.7.0_85, vendor: Oracle Corporation
Java home: D:\java\jdk1.7.0_85\jre
Default locale: en_IE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"`

Thank you in advance ! :D

**Comment by eirslett** [comment]
Try using a newer version of the plugin and a newer version of maven?

**Comment by math29** [comment]
Thank you for your answer :)

I already tried with the last versions of maven, nodejs, npm and frontend-maven-plugin but it didn't change anything ..

**Comment by eirslett** [comment]
This error comes from gulp: 'images-catalogue' errored after 1.07 s

Try running the gulp build without maven?

**Comment by math29** [comment]
Yes this is the point, it works fine when I execute it without maven.

It works fine as well when I execute it in my Jenkins environment, but I don't find out why it do not works in local on my computer.

It looks like there are specific plugins from gulp-load-plugins that do not works when I execute this maven install

**Comment by mriehema** [comment]
Update your Maven 3.0.4 to at least 3.1

@eirslett We should fix the Readme: https://github.com/eirslett/frontend-maven-plugin#requirements

**Comment by math29** [comment]
I already tried and I have exactly the same error : 
`
\apache-maven-3.3.9\bin\mvn clean install
...
[INFO] --- frontend-maven-plugin:0.0.22:gulp (gulp build) @ aat ---
[INFO] Running 'gulp build --no-color' in C:\Users\mallain\workspace\aat-ui\application
[INFO] [13:34:18] Using gulpfile ~\workspace\aat-ui\application\gulpfile.js
[INFO] [13:34:18] Starting 'build'...
[INFO] [13:34:19] Starting 'clean'...
[INFO] [13:34:19] Finished 'clean' after 64 ms
[INFO] [13:34:19] Starting 'wiredep'...
[INFO] [13:34:19] Starting 'eslint'...
[INFO] [13:34:22] Starting 'templateCache'...
[INFO] [13:34:25] Starting 'images-theme-svg'...
[INFO] [13:34:25] Starting 'images-catalogue'...
[INFO] [13:34:29] 'images-catalogue' errored after 3.83 s
[INFO] [13:34:29] C:\Users\mallain\workspace\aat-ui\application\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs\node_modules\gulp-sourcemaps\index.js:38
[INFO]     debug(() => {return options;});
[INFO]            ^
[INFO] SyntaxError: Unexpected token )
[INFO]     at exports.runInThisContext (vm.js:73:16)
[INFO]     at Module._compile (module.js:443:25)
[INFO]     at Object.Module._extensions..js (module.js:478:10)
[INFO]     at Module.load (module.js:355:32)
[INFO]     at Function.Module._load (module.js:310:12)
[INFO]     at Module.require (module.js:365:17)
[INFO]     at require (module.js:384:17)
[INFO]     at Object.<anonymous> (C:\Users\mallain\workspace\aat-ui\application\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs\lib\src\index.js:8:18)
[INFO]     at Module._compile (module.js:460:26)
[INFO]     at Object.Module._extensions..js (module.js:478:10)
[INFO]     at Module.load (module.js:355:32)
[INFO]     at Function.Module._load (module.js:310:12)
[INFO]     at Module.require (module.js:365:17)
[INFO]     at require (module.js:384:17)
[INFO]     at Object.<anonymous> (C:\Users\mallain\workspace\aat-ui\application\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs\index.js:4:8)
[INFO]     at Module._compile (module.js:460:26)
[INFO]     at Object.Module._extensions..js (module.js:478:10)
[INFO]     at Module.load (module.js:355:32)
[INFO]     at Function.Module._load (module.js:310:12)
[INFO]     at Module.require (module.js:365:17)
[INFO]     at require (module.js:384:17)
[INFO]     at Object.<anonymous> (C:\Users\mallain\workspace\aat-ui\application\node_modules\gulp-imagemin\node_modules\imagemin\index.js:7:15)
[INFO] [13:34:29] 'build' errored after 11 s
[INFO] [13:34:29] Error in plugin 'run-sequence'
[INFO] Message:
[INFO]     An error occured in task 'images-catalogue'.
[INFO] [13:34:37] Finished 'wiredep' after 19 s
[INFO] [13:34:38] all files 34.71 kB
[INFO] [13:34:38] Finished 'images-theme-svg' after 13 s
[INFO] [13:34:38] Finished 'templateCache' after 16 s
[INFO] [13:34:41]
[INFO] C:\Users\mallain\workspace\aat-ui\application\test\e2e\app\errorPopup.spec.js
[INFO]   8:53  warning  Block must not be padded by blank lines  padded-blocks
[INFO]
[INFO] C:\Users\mallain\workspace\aat-ui\application\test\spec\services\applicationList.service.spec.js
[INFO]   57:21  warning  You should use the array syntax for DI  angular/di
[INFO]
[INFO] C:\Users\mallain\workspace\aat-ui\application\test\spec\services\states.service.spec.js
[INFO]   49:12  warning  You should use the array syntax for DI  angular/di
[INFO]
[INFO] C:\Users\mallain\workspace\aat-ui\application\test\spec\app\mainView\mainView.controller.spec.js
[INFO]   31:21  warning  You should use the array syntax for DI  angular/di
[INFO]   38:21  warning  You should use the array syntax for DI  angular/di
[INFO]
[INFO] Γ£û 5 problems (0 errors, 5 warnings)
[INFO]
[INFO] [13:34:41] Finished 'eslint' after 22 s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:34 min
[INFO] Finished at: 2016-12-13T13:34:41+01:00
[INFO] Final Memory: 14M/154M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:gulp (gulp build) on project aat: Failed to run task: 'gulp build --no-color' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by eirslett** [comment]
@math29 Try this:

```
npm install -g gulp
gulp build
```

does the build succeed?

**Comment by math29** [comment]
npm install -g gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree. C:\Program Files\nodejs\gulp -> C:\Program Files\nodejs\node_modules\gulp\bin\gulp.js
gulp@3.9.1 C:\Program Files\nodejs\node_modules\gulp
├── interpret@1.0.1
├── pretty-hrtime@1.0.3
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.2.0 (os-homedir@1.0.2)
├── semver@4.3.6
├── v8flags@2.0.11 (user-home@1.1.1)
├── chalk@1.1.3 (ansi-styles@2.2.1, escape-string-regexp@1.0.5, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── orchestrator@0.3.8 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── vinyl-fs@0.3.14 (strip-bom@1.0.0, vinyl@0.4.6, graceful-fs@3.0.11, defaults@1.0.3, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)
├── liftoff@2.3.0 (lodash.isplainobject@4.0.6, lodash.isstring@4.0.1, lodash.mapvalues@4.6.0, rechoir@0.6.2, extend@3.0.0, flagged-respawn@0.3.2, resolve@1.1.7, fined@1.0.2, findup-sync@0.4.3)
└── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, array-uniq@1.0.3, object-assign@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.1, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.3, multipipe@0.1.2, dateformat@1.0.12)

"C:\Program Files\nodejs\gulp" build  (or gulp build)                                                           
[14:09:38] Using gulpfile ~\workspace\aat-ui\application\gulpfile.js                                            
[14:09:38] Starting 'build'...                                                                                  
[14:09:38] Starting 'clean'...                                                                                  
[14:09:38] Finished 'clean' after 77 ms                                                                         
[14:09:38] Starting 'wiredep'...                                                                                
[14:09:38] Starting 'eslint'...                                                                                 
[14:09:39] Starting 'templateCache'...                                                                          
[14:09:40] Starting 'images-theme-svg'...                                                                       
[14:09:40] Starting 'images-catalogue'...                                                                       
[14:09:44] Starting 'font-awesome'...                                                                           
[14:09:44] Starting 'glyphicons'...                                                                             
[14:09:44] Starting 'copy-popup-html'...                                                                        
[14:09:44] Starting 'copy-error-popup-html'...                                                                  
[14:09:48] Finished 'wiredep' after 10 s                                                                        
[14:09:49] all files 133 B                                                                                      
[14:09:49] Finished 'copy-popup-html' after 4.62 s                                                              
[14:09:49] all files 825 B                                                                                      
[14:09:49] Finished 'copy-error-popup-html' after 4.62 s                                                        
[14:09:49] all files 34.71 kB                                                                                   
[14:09:49] Finished 'images-theme-svg' after 9.35 s                                                             
[14:09:49] Starting 'images-theme'...                                                                           
[14:09:50] all files 215.72 kB                                                                                  
[14:09:50] Finished 'glyphicons' after 5.88 s                                                                   
[14:09:50] all files 728.71 kB                                                                                  
[14:09:50] Finished 'font-awesome' after 5.9 s                                                                  
[14:09:51]                                                                                                      
*****.spec.js                                   
  8:53  warning  Block must not be padded by blank lines  padded-blocks                                         
                                                                                                                
*******.spec.js                
  57:21  warning  You should use the array syntax for DI  angular/di                                            
                                                                                                                
******.spec.js                         
  49:12  warning  You should use the array syntax for DI  angular/di                                            
                                                                                                                
******.spec.js                
  31:21  warning  You should use the array syntax for DI  angular/di                                            
  38:21  warning  You should use the array syntax for DI  angular/di                                            
                                                                                                                
✖ 5 problems (0 errors, 5 warnings)                                                                             
                                                                                                                
[14:09:51] Finished 'eslint' after 13 s                                                                         
[14:09:51] Starting 'scripts'...                                                                                
[14:09:52] Finished 'templateCache' after 13 s                                                                  
[14:09:52] all files 15.15 kB                                                                                   
[14:09:52] Finished 'scripts' after 930 ms                                                                      
[14:09:52] Starting 'html'...                                                                                   
[14:10:01] gulp-imagemin: Minified 16 images (saved 8.71 kB - 39%)                                              
[14:10:02] gulp-imagemin: Minified 8 images (saved 0 B - 0%)                                                    
[14:10:02] all files 123.28 kB                                                                                  
[14:10:02] Finished 'images-catalogue' after 22 s                                                               
[14:10:03] all files 13.6 kB                                                                                    
[14:10:03] Finished 'images-theme' after 13 s                                                                   
[14:10:28] all files 1.53 MB                                                                                    
[14:10:28] Finished 'html' after 36 s                                                                           
[14:10:28] Finished 'build' after 50 s 

So yes, the build works fine even with gulp installed in global :)

**Comment by javimaravillas** [comment]
Hi guys,
I think I have found the issue or one related to the goal gulp.
When I force a gulp goal, I got "mvn com.github.eirslett:frontend-maven-plugin:1.3:gulp"
Then the ouput is:
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:gulp (default-cli) on project bitu-key-manager-website: Failed to run task: 'gulp.js ' failed. (error code 1) -> [Help 1]

Take attention to "gulp.js", gulp should be called without .js.

I have fix this issue and submit a pull request:
https://github.com/eirslett/frontend-maven-plugin/pull/558

Regards,

**Comment by math29** [comment]
On my side, I have this :
 Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:gulp (gulp build) on project aat: Failed to run task: 'gulp build --no-color' failed. (error code 1)

So I'm not concerned by this issue

**Comment by math29** [comment]
Ok, I finally figured out that one nodejs was broken. I reinstalled the all thing and it works fine now. Thank you all :)

**Comment by fragaLY** [comment]
If you are using https://spring.io/guides/tutorials/react-and-spring-data-rest/ be care.
Please check the structure of your project it should not contain any previous node packages, package-lock.json and etc.

Then you could run clean install and you could find that exception disapears.
