### ISSUE TITLE
 gulp doesn't work in frontend-maven-plugin 1.4

### ISSUE THREAD

**Issue by 40rn05lyv** [eirslett/frontend-maven-plugin#586]
Following configuration worked ok in 1.3, but doesn't work in 1.4.

Pom config:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>ppp1</groupId>
	<artifactId>ppp1</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>1.4</version>
				<executions>
					<execution>
						<id>default-cli</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>v6.9.1</nodeVersion>
							<npmVersion>3.10.8</npmVersion>
						</configuration>
					</execution>
					<execution>
						<id>npm-install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install --cache "C:\Users\user1/.npm-cache/my-folder/" --unicode=false</arguments>
						</configuration>
					</execution>
					<execution>
						<id>gulp build</id>
						<goals>
							<goal>gulp</goal>
						</goals>
                        <!-- optional: the default phase is "generate-resources" -->
                        <phase>generate-resources</phase>
					</execution>
				</executions>
				<configuration>
					<installDirectory>C:\Users\user1/.frontend-node/my-folder/</installDirectory>
				</configuration>
			</plugin>

		</plugins>
	</build>
</project>


```

Error:

```
[INFO] --- frontend-maven-plugin:1.4:npm (npm-install) @ ppp1 ---
[INFO] Running 'npm install --cache "C:\Users\user1/.npm-cache/my-folder/" --unicode=false' in D:\development\workspaces\workspace_1\ppp1
[INFO] 
[INFO] --- frontend-maven-plugin:1.4:gulp (gulp build) @ ppp1 ---
[INFO] Running 'gulp ' in D:\development\workspaces\workspace_1\ppp1
[ERROR] module.js:471
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module 'C:\Users\user1\.frontend-node\my-folder\node_modules\gulp\bin\gulp'
[ERROR]     at Function.Module._resolveFilename (module.js:469:15)
[ERROR]     at Function.Module._load (module.js:417:25)
[ERROR]     at Module.runMain (module.js:604:10)
[ERROR]     at run (bootstrap_node.js:394:7)
[ERROR]     at startup (bootstrap_node.js:149:9)
[ERROR]     at bootstrap_node.js:509:3
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.312 s
[INFO] Finished at: 2017-03-30T15:07:19+03:00
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:gulp (gulp build) on project ppp1: Failed to run task: 'gulp ' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
```

**Comment by mriehema** [comment]
Do you get the same error without a different `installDirectory `configuration?

```
<configuration>
	<installDirectory>C:\Users\user1/.frontend-node/my-folder/</installDirectory>
</configuration>
```

**Comment by mriehema** [comment]
Maybe PR #434 is causing your problem.

**Comment by arey** [comment]
We have a similar issue in Spring Petclinic AngularJS: https://github.com/spring-petclinic/spring-petclinic-angular1/issues/10
By removing the installDirectory configuration, gulp works fine again.

**Comment by cowwoc** [comment]
@Antibrumm @eirslett

This issue is definitely caused by #434. Specifically, https://github.com/eirslett/frontend-maven-plugin/pull/434/commits/3ebc007c057303f457440f47dfa0c651be359d04 is meant to ensure that `WorkingDir` gets used before `InstallDir` but https://github.com/eirslett/frontend-maven-plugin/blob/7788bf4fb385159170a9de338522f614fabd19ce/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/GulpRunner.java#L6 implies that gulp must be found at `WorkingDir/node_modules/gulp/bin/gulp`; otherwise `InstallDir` gets used.

Here's the kicker, in my installation the only file in `node_modules\gulp\bin` is `gulp.js` which means that `InstallDir` always gets used (which is incorrect).

**Comment by arey** [comment]
@cowwoc do you have any idea why https://github.com/spring-petclinic/spring-petclinic-angularjs/blob/master/pom.xml is not working with the 1.4 version? If I remove the installDirectory configuration, it works again.

**Comment by cowwoc** [comment]
@arey Not sure. I can only speak for my case as I walked through the code. Sorry I couldn't be of more help.

**Comment by Antibrumm** [comment]
I think I found at least a part of the issue. I'm not using Gulp but Grunt and there the TASK_LOCATION seems correct, i.e. there is really a file just called "grunt". This does not seem valid for the TASK_LOCATION in the **DefaultGulpRunner**. 

Probably an easy first fix would be to correct that property.

**Comment by arey** [comment]
Same issue with the 1.5 version

**Comment by mgohin** [comment]
Looks like it didn't change in 1.6

**Comment by vojtechhabarta** [comment]
I have the same problem.
It seems fix is in master, @eirslett could you please release it?

**Comment by phare2013** [comment]
There isn't an answer to @vojtechhabarta...So I was curious as to if there was in fact a fix merged. I am currently using 1.6 and it is failing to run a task that I know is available. 

Thank you in advanced.

**Comment by hongyu-wang** [comment]
+1

**Comment by eirslett** [comment]
1.7.5 is the latest release.
