### ISSUE TITLE
Jenkins build on RPI3 fails with 

### ISSUE THREAD

**Issue by legolas** [eirslett/frontend-maven-plugin#608]
**Do you want to request a _feature_ or report a _bug_?**
Bug
**What is the current behavior?**
Doing a maven build from jenkins on JBoss on Raspberry PI 3 fails with this stack:
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:121)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'npm install' failed.
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:63)
	at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:62)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:115)
	... 22 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutionException: org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
	at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute(ProcessExecutor.java:82)
	at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput(ProcessExecutor.java:64)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeExecutor.executeAndRedirectOutput(NodeExecutor.java:29)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:58)
	... 24 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute(ProcessExecutor.java:74)
	... 27 more
[[1;31mERROR[m] 
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The build succeeds without error
**Please mention your frontend-maven-plugin and operating system version.**
1.4

This is the configuration:
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.4</version>

                <configuration>
                    <nodeVersion>v6.10.3</nodeVersion>
                    <npmVersion>4.6.1</npmVersion>
                    <workingDirectory>src/main/frontend</workingDirectory>
                    <installDirectory>target</installDirectory>
                </configuration>

                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>coverage</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            
                            <skip>true</skip>
                            <arguments>run-script coverage</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm build for production</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>run-script prod</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by mriehema** [comment]
Sorry, but your part of the maven log is not showing enough details. Is the same configuration running on other systems?

**Comment by legolas** [comment]
Thank you for your response, Michael.
The build does work fine on my laptop.
When I disable the frontend-maven-plugin the build also succeeds on the PI.
I want to use my PI for CI/CD of a [IoT project](/legolas/sonoff-mqtt-iot) I'm currently working on.

What information is missing from the logs?

Regards,
Marcel

**Comment by mriehema** [comment]
Maybe a problem with the ARM version of node or wrong platform detection. Which node/npm files are downloaded? At which execution is mvn stopping? Could you give us the full log?

**Comment by legolas** [comment]
Node is v7.10.0 npm has 4.2.0.
I will provide the full log tonight when I back home.

**Comment by legolas** [comment]
Here is the log file, sorry for the delay.
[log.zip](https://github.com/eirslett/frontend-maven-plugin/files/1032926/log.zip)

**Comment by mriehema** [comment]
Your log says:

> Unpacking /home/jboss/.m2/repository/com/github/eirslett/node/6.10.3/node-6.10.3-linux-x86.tar.gz

But RPI3 needs `node-v6.10.3-linux-armv6l.tar.xz`. Right now, this plugin does not support arm versions.

**Comment by legolas** [comment]
OK, so that means I need to rely on installed versions of both node and npm?
How do I configure that?

**Comment by mriehema** [comment]
I'm sorry to tell you, that this is not possible. If you want to rely on installed node version, you should use the maven-exec-plugin instead. You can open a new issue as feature request for supporting RPI3/arm platforms, but I am afraid, that this will not happen soon.

**Comment by legolas** [comment]
Thanks, I will update my pom and abandon the frontend-maven-plugin for this project.
