### ISSUE TITLE
"command not found error" executing a global installed package

### ISSUE THREAD

**Issue by Ginxo** [eirslett/frontend-maven-plugin#859]
**frontend-maven-plugin**: 1.7.5
**Environment**: 

- **OS**: OS name: "linux", version: "5.2.8-200.fc30.x86_64", arch: "amd64", family: "unix"
- **java**: Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
- **maven**: Apache Maven 3.5.4

**Type issue**: question/bug?
**Current behavior**: can't execute global npm packages
**Steps to reproduce it**:

- Add a `install -g npm-treatment-tools` npm execution to the frontend-maven-plugin
- Add the script `"lock-remove": "npmtt remove"` to a package.json file
- Add the `run lock-remove` npm execution to the frontend-maven-plugin
- Execute maven

**Expected behavior**: To be able to execute global packages

**Plugin configuration**
```
      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>install node and npm</id>
            <phase>initialize</phase>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>v8.12.0</nodeVersion>
              <npmVersion>6.9.0</npmVersion>
            </configuration>
          </execution>
          <execution>
            <id>npm install treatment tools</id>
            <phase>initialize</phase>
            <goals>
              <goal>npm</goal>
            </goals>
            <configuration>
              <arguments>install -g npm-treatment-tools</arguments>
            </configuration>
          </execution>
          <execution>
            <id>npm treat lock files</id>
            <phase>compile</phase>
            <goals>
              <goal>npm</goal>
            </goals>
            <configuration>
              <arguments>run lock-remove</arguments>
            </configuration>
          </execution>
...
...
```
**The package.json**
```
{
  "name": "project",
  "homepage": ".",
  "private": true,
  "license": "Apache-2.0",
  "scripts": {
    "lock-remove": "npmtt remove"
  },
  "devDependencies": {
    "npm-treatment-tools": "^1.1.1" // this is not needed for this case
  }
}

```

**The maven logs**
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----< prorject-groupId:project-artifactId >-----
[INFO] Building project
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ project-artifactId ---
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.5:install-node-and-npm (install node and npm) @ project-artifactId ---
[INFO] Node v8.12.0 is already installed.
[INFO] NPM 6.9.0 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.5:npm (npm install treatment tools) @ project-artifactId ---
[INFO] Running 'npm install -g npm-treatment-tools' in /project-folder
[INFO] /project-folder/bin/npmtt -> /project-folder/lib/node_modules/npm-treatment-tools/bin/npmtt.js
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/npm-treatment-tools/node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
[INFO] + npm-treatment-tools@1.1.1
[INFO] added 305 packages from 204 contributors in 11.282s
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.5:npm (npm treat lock files) @ project-artifactId ---
[INFO] Running 'npm run lock-remove' in /project-folder
[INFO] 
[INFO] > project-artifactId@ lock-remove /project-folder
[INFO] > npmtt remove
[INFO] 
[ERROR] sh: npmtt: command not found
[ERROR] npm ERR! file sh
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno ENOENT
[ERROR] npm ERR! syscall spawn
[ERROR] npm ERR! project-artifactId@ lock-remove: `npmtt remove`
[ERROR] npm ERR! spawn ENOENT
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the project-artifactId@ lock-remove script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[WARNING] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/user/.npm/_logs/2019-10-24T06_30_19_592Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.310 s
[INFO] Finished at: 2019-10-24T08:30:19+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:npm (npm treat lock files) on project project-artifactId: Failed to run task: 'npm run lock-remove' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

The  /home/user/.npm/_logs/2019-10-24T06_30_19_592Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/project-folder/node/node',
1 verbose cli   '/project-folder/node/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lock-remove' ]
2 info using npm@6.9.0
3 info using node@v8.12.0
4 verbose run-script [ 'prelock-remove', 'lock-remove', 'postlock-remove' ]
5 info lifecycle project-artifactId@~prelock-remove: project-artifactId@
6 info lifecycle project-artifactId@~lock-remove: project-artifactId@
7 verbose lifecycle project-artifactId@~lock-remove: unsafe-perm in lifecycle true
8 verbose lifecycle project-artifactId@~lock-remove: PATH: /project-folder/node/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/project-folder/node_modules/.bin:/project-folder/node:/home/user/.local/bin:/home/user/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:true:/usr/local/git/bin:/home/user/development/software/apache-maven-3.5.4-prod/bin:/usr/java/jdk1.8.0_212-amd64/bin:true:/usr/local/git/bin:/home/user/development/software/apache-maven-3.5.4-prod/bin:/usr/java/jdk1.8.0_212-amd64/bin:
9 verbose lifecycle project-artifactId@~lock-remove: CWD: /project-folder
10 silly lifecycle project-artifactId@~lock-remove: Args: [ '-c', 'npmtt remove' ]
11 info lifecycle project-artifactId@~lock-remove: Failed to exec lock-remove script
12 verbose stack Error: project-artifactId@ lock-remove: `npmtt remove`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/project-folder/node/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:915:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid project-artifactId@
14 verbose cwd /project-folder
15 verbose Linux 5.2.8-200.fc30.x86_64
16 verbose argv "/project-folder/node/node" "/project-folder/node/node_modules/npm/bin/npm-cli.js" "run" "lock-remove"
17 verbose node v8.12.0
18 verbose npm  v6.9.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error project-artifactId@ lock-remove: `npmtt remove`
23 error spawn ENOENT
24 error Failed at the project-artifactId@ lock-remove script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by eirslett** [comment]
Don't install the tool globally, install it locally.

**Comment by Ginxo** [comment]
I solved it runing `npm install npm-treatment-tools --global-style --no-package-lock`
